unit csErrorCodes;

interface

const
  ERROR_CAD_GENERAL = 1000;
  ERROR_CAD_INVALID_HANDLE = ERROR_CAD_GENERAL + 1;
  ERROR_CAD_INVALID_INDEX = ERROR_CAD_GENERAL + 2;
  ERROR_CAD_FILE_NOT_FOUND = ERROR_CAD_GENERAL + 3;
  ERROR_CAD_FILE_READ = ERROR_CAD_GENERAL + 4;
  ERROR_CAD_INVALID_CADDRAW = ERROR_CAD_GENERAL + 5;
  ERROR_CAD_UNSUPFORMAT_FILE = ERROR_CAD_GENERAL + 6;
implementation
end.
