SET SQL DIALECT 3;

CREATE TABLE PROJECTS (
    ID                ID /* ID = INTEGER DEFAULT 0 NOT NULL */,
    ADDRESS           LONG_NAME /* LONG_NAME = VARCHAR(120) DEFAULT '' */,
    DOC_NUMBER        NUMBER_CHAR /* NUMBER_CHAR = VARCHAR(12) */,
    DOC_DATE          TIMESTAMP,
    CUSTOMER_ORGS_ID  INTEGER,
    CONFIRMED         IBBOOL /* IBBOOL = SMALLINT DEFAULT 0 NOT NULL CHECK (VALUE IN (0, 1)) */,
    EXECUTOR_ORGS_ID  INTEGER,
    CONFIRM_DATE      TIMESTAMP,
    MINX              COORD NOT NULL /* COORD = NUMERIC(15,2) */,
    MINY              COORD NOT NULL /* COORD = NUMERIC(15,2) */,
    MAXX              COORD NOT NULL /* COORD = NUMERIC(15,2) */,
    MAXY              COORD NOT NULL /* COORD = NUMERIC(15,2) */,
    CK36              IBBOOL /* IBBOOL = SMALLINT DEFAULT 0 NOT NULL CHECK (VALUE IN (0, 1)) */,
    TMP               COORD /* COORD = NUMERIC(15,2) */
);
ALTER TABLE PROJECTS ADD CONSTRAINT PK_PROJECTS PRIMARY KEY (ID);
ALTER TABLE PROJECTS ADD CONSTRAINT FK_PROJECTS_1 FOREIGN KEY (CUSTOMER_ORGS_ID) REFERENCES LICENSED_ORGS (ID);
ALTER TABLE PROJECTS ADD CONSTRAINT FK_PROJECTS_2 FOREIGN KEY (EXECUTOR_ORGS_ID) REFERENCES LICENSED_ORGS (ID);
DESCRIBE FIELD CUSTOMER_ORGS_ID TABLE PROJECTS
'Указывает на LICENSED_ORGS_ID.';
DESCRIBE FIELD CONFIRMED TABLE PROJECTS
'Согласованно или нет.';
DESCRIBE FIELD EXECUTOR_ORGS_ID TABLE PROJECTS
'Указывает на LICENSED_ORGS_ID.';
/* Privileges of users */
GRANT ALL ON PROJECTS TO PUBLIC;


CREATE TABLE PROJECT_LAYERS (
    ID           ID NOT NULL /* ID = INTEGER DEFAULT 0 NOT NULL */,
    NAME         STRING255 NOT NULL /* STRING255 = VARCHAR(255) */,
    REQUIRED     IBBOOL /* IBBOOL = SMALLINT DEFAULT 0 NOT NULL CHECK (VALUE IN (0, 1)) */,
    DESTROYED    IBBOOL /* IBBOOL = SMALLINT DEFAULT 0 NOT NULL CHECK (VALUE IN (0, 1)) */,
    OBJECT_TYPE  SMALLINT NOT NULL
);
ALTER TABLE PROJECT_LAYERS ADD CONSTRAINT PK_PROJECT_LAYERS PRIMARY KEY (ID);
DESCRIBE TABLE PROJECT_LAYERS
'Слои проекта';
DESCRIBE FIELD NAME TABLE PROJECT_LAYERS
'Имя слоя в файле AUTOCAD';
DESCRIBE FIELD REQUIRED TABLE PROJECT_LAYERS
'1 - обязаьельный слой
2 - необязательный слой';
DESCRIBE FIELD DESTROYED TABLE PROJECT_LAYERS
'0 - для проектируемых
1 - для выводимых из эксплуатации';
DESCRIBE FIELD OBJECT_TYPE TABLE PROJECT_LAYERS
'0 - для линий
1 - для точечных объектов';
/* Privileges of users */
GRANT ALL ON PROJECT_LAYERS TO PUBLIC;

CREATE TABLE PROJECT_LINES (
    ID                 ID NOT NULL /* ID = INTEGER DEFAULT 0 NOT NULL */,
    PROJECTS_ID        ID /* ID = INTEGER DEFAULT 0 NOT NULL */,
    INFO               BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    DIAMETER           STRING50 /* STRING50 = VARCHAR(50) */,
    VOLTAGE            STRING50 /* STRING50 = VARCHAR(50) */,
    PROJECT_LAYERS_ID  ID NOT NULL /* ID = INTEGER DEFAULT 0 NOT NULL */
);
ALTER TABLE PROJECT_LINES ADD CONSTRAINT PK_PROJECT_LINES PRIMARY KEY (ID);
ALTER TABLE PROJECT_LINES ADD CONSTRAINT FK_PROJECT_LINES_1 FOREIGN KEY (PROJECTS_ID) REFERENCES PROJECTS (ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PROJECT_LINES ADD CONSTRAINT FK_PROJECT_LINES_3 FOREIGN KEY (PROJECT_LAYERS_ID) REFERENCES PROJECT_LAYERS (ID) ON UPDATE CASCADE;
DESCRIBE TABLE PROJECT_LINES
'Осевые линии проекта';
/* Privileges of users */
GRANT ALL ON PROJECT_LINES TO PUBLIC;

ALTER TABLE PEOPLE
ADD CAN_MS_PROJIECTS IBBOOL;

update people set CAN_MS_PROJIECTS = 0;

CREATE TABLE PROJECT_BLOCKS (
    ID           ID NOT NULL /* ID = INTEGER DEFAULT 0 NOT NULL */,
    PROJECTS_ID  ID /* ID = INTEGER DEFAULT 0 NOT NULL */,
    NAME         STRING100 /* STRING100 = VARCHAR(100) */,
    EZDATA       BLOB SUB_TYPE 0 SEGMENT SIZE 80
);
ALTER TABLE PROJECT_BLOCKS ADD CONSTRAINT PK_PROJECT_BLOCKS PRIMARY KEY (ID);
ALTER TABLE PROJECT_BLOCKS ADD CONSTRAINT FK_PROJECT_BLOCKS_1 FOREIGN KEY (PROJECTS_ID) REFERENCES PROJECTS (ID) ON DELETE CASCADE ON UPDATE CASCADE;
DESCRIBE TABLE PROJECT_BLOCKS
'Блоки, используемые в проекте для точечных объектов';
/* Privileges of users */
GRANT ALL ON PROJECT_BLOCKS TO PUBLIC;

CREATE TABLE PROJECT_OBJECTS (
    ID                 ID NOT NULL /* ID = INTEGER DEFAULT 0 NOT NULL */,
    PROJECTS_ID        ID /* ID = INTEGER DEFAULT 0 NOT NULL */,
    NAME               STRING100 /* STRING100 = VARCHAR(100) */,
    OBJECT_TYPE        INTEGER NOT NULL,
    EZDATA             BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    PROJECT_BLOCKS_ID  INTEGER,
    PROJECT_LAYERS_ID  INTEGER
);
ALTER TABLE PROJECT_OBJECTS ADD CONSTRAINT PK_PROJECT_OBJECTS PRIMARY KEY (ID);
ALTER TABLE PROJECT_OBJECTS ADD CONSTRAINT FK_PROJECT_OBJECTS_1 FOREIGN KEY (PROJECTS_ID) REFERENCES PROJECTS (ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PROJECT_OBJECTS ADD CONSTRAINT FK_PROJECT_OBJECTS_2 FOREIGN KEY (PROJECT_BLOCKS_ID) REFERENCES PROJECT_BLOCKS (ID);
ALTER TABLE PROJECT_OBJECTS ADD CONSTRAINT FK_PROJECT_OBJECTS_3 FOREIGN KEY (PROJECT_LAYERS_ID) REFERENCES PROJECT_LAYERS (ID) ON DELETE CASCADE ON UPDATE CASCADE;
DESCRIBE TABLE PROJECT_OBJECTS
'Точеченые и другие дополнительные объекты в проекте';
DESCRIBE FIELD OBJECT_TYPE TABLE PROJECT_OBJECTS
'Тип объекта:
0 - точечный объект
1 - текст
2 - прочее';
/* Privileges of users */
GRANT ALL ON PROJECT_OBJECTS TO PUBLIC;

CREATE TABLE PROJECT_LINES (
    ID                 ID NOT NULL /* ID = INTEGER DEFAULT 0 NOT NULL */,
    PROJECTS_ID        ID /* ID = INTEGER DEFAULT 0 NOT NULL */,
    INFO               BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    DIAMETER           STRING50 /* STRING50 = VARCHAR(50) */,
    VOLTAGE            STRING50 /* STRING50 = VARCHAR(50) */,
    PROJECT_LAYERS_ID  ID NOT NULL /* ID = INTEGER DEFAULT 0 NOT NULL */
);
ALTER TABLE PROJECT_LINES ADD CONSTRAINT PK_PROJECT_LINES PRIMARY KEY (ID);
ALTER TABLE PROJECT_LINES ADD CONSTRAINT FK_PROJECT_LINES_1 FOREIGN KEY (PROJECTS_ID) REFERENCES PROJECTS (ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PROJECT_LINES ADD CONSTRAINT FK_PROJECT_LINES_3 FOREIGN KEY (PROJECT_LAYERS_ID) REFERENCES PROJECT_LAYERS (ID) ON UPDATE CASCADE;
DESCRIBE TABLE PROJECT_LINES
'Осевые линии проекта';
/* Privileges of users */
GRANT ALL ON PROJECT_LINES TO PUBLIC;

CREATE TABLE PROJECT_LINE_POINTS (
    ID                ID NOT NULL /* ID = INTEGER DEFAULT 0 NOT NULL */,
    PROJECT_LINES_ID  ID /* ID = INTEGER DEFAULT 0 NOT NULL */,
    X                 COORD /* COORD = NUMERIC(15,2) */,
    Y                 COORD /* COORD = NUMERIC(15,2) */,
    Z                 COORD /* COORD = NUMERIC(15,2) */
);
ALTER TABLE PROJECT_LINE_POINTS ADD CONSTRAINT PK_PROJECT_LINE_POINTS PRIMARY KEY (ID);
ALTER TABLE PROJECT_LINE_POINTS ADD CONSTRAINT FK_PROJECT_LINE_POINTS_1 FOREIGN KEY (PROJECT_LINES_ID) REFERENCES PROJECT_LINES (ID) ON DELETE CASCADE ON UPDATE CASCADE;
DESCRIBE TABLE PROJECT_LINE_POINTS
'Точки осевых линий проекта';
/* Privileges of users */
GRANT ALL ON PROJECT_LINE_POINTS TO PUBLIC;

CREATE GENERATOR PROJECTS_GEN;
CREATE GENERATOR PROJECT_LINES_GEN;
CREATE GENERATOR PROJECT_LINE_POINTS_GEN;

INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (23, '121-122-В-Трубопровод водопровод', 1, 0, 0);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (7, '117-В-Смотровой колодец водопровод', 1, 0, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (25, '121-122-Г-Трубопровод газопровод', 1, 0, 0);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (9, '117-Г-Смотровой колодец газопровод', 1, 0, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (27, '121-122-Г-Трубопровод теплотрасса', 1, 0, 0);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (11, '117-Г-Смотровой колодец теплотрасса', 1, 0, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (37, '123-127-Лотки-камеры-каналы-коллекторы', 1, 0, 0);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (31, '121-122-К-Трубопровод канализация', 1, 0, 0);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (15, '117-К-Смотровой колодец канализация', 1, 0, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (33, '121-122-Кл-Трубопровод канализация ливневая', 1, 0, 0);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (17, '117-Кл-Смотровой колодец канализация ливневая', 1, 0, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (39, '128-Рештки сточные', 1, 0, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (1, '106-108 Опоры', 1, 0, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (3, '114-116-119 Электрокабели', 1, 0, 0);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (21, '117-Смотровой колодец электрокабели', 1, 0, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (41, '133-134-V-Линии связи', 1, 0, 0);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (5, '117-V-Смотровой колодец линии связи', 1, 0, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (35, '121-122-Н-Трубопровод нефтепроводы', 1, 0, 0);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (19, '117-Н-Смотровой колодец нефтепроводы', 1, 0, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (29, '121-122-ГК-Трубопровод кислородопровод', 1, 0, 0);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (13, '117-ГК-Смотровой колодец кислородопровод', 1, 0, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (42, 'NOT-133-134-V-Линии связи', 1, 1, 0);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (40, 'NOT-128-Рештки сточные', 1, 1, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (2, 'NOT-106-108-Опоры', 1, 1, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (4, 'NOT-114-116-119-Электрокабели', 1, 1, 0);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (38, 'NOT-123-127-Лотки-камеры-каналы-коллекторы', 1, 1, 0);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (6, 'NOT-117-V-Смотровой колодец линии связи', 1, 1, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (36, 'NOT-121-122-Н-Трубопровод нефтепроводы', 1, 1, 0);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (8, 'NOT-117-В-Смотровой колодец водопровод', 1, 1, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (34, 'NOT-121-122-Кл-Трубопровод канализация ливневая', 1, 1, 0);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (10, 'NOT-117-В-Смотровой колодец водопровод', 1, 1, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (32, 'NOT-121-122-К-Трубопровод канализация', 1, 1, 0);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (12, 'NOT-117-Г-Смотровой колодец теплотрасса', 1, 1, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (30, 'NOT-121-122-ГК-Трубопровод кислородопровод', 1, 1, 0);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (14, 'NOT-117-ГК-Смотровой колодец кислородопровод', 1, 1, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (28, 'NOT-121-122-Г-Трубопровод теплотрасса', 1, 1, 0);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (16, 'NOT-117-К-Смотровой колодец канализация', 1, 1, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (26, 'NOT-121-122-Г-Трубопровод газопровод', 1, 1, 0);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (18, 'NOT-117-Кл-Смотровой колодец канализация ливневая', 1, 1, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (24, 'NOT-121-122-В-Трубопровод водопровод', 1, 1, 0);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (22, 'NOT-117-Смотровой колодец электрокабели', 1, 1, 1);
INSERT INTO PROJECT_LAYERS (ID, NAME, REQUIRED, DESTROYED, OBJECT_TYPE)
                    VALUES (20, 'NOT-117-Н-Смотровой колодец нефтепроводы', 1, 1, 1);

COMMIT WORK;
