SET SQL DIALECT 3;

CREATE TABLE LAYERS_SEMANTIC (
    ID           INTEGER DEFAULT 0 NOT NULL,
    LAYERS_ID    INTEGER DEFAULT 0 NOT NULL,
    OBJECT_ID    VARCHAR(36),
    FIELD_NAME   VARCHAR(255),
    FIELD_VALUE  BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    FIELD_TYPE   VARCHAR(50) COLLATE PXW_CYRL
);
ALTER TABLE LAYERS_SEMANTIC ADD CONSTRAINT PK_LAYERS_SEMANTIC PRIMARY KEY (ID);
ALTER TABLE LAYERS_SEMANTIC ADD CONSTRAINT FK_LAYERS_SEMANTIC_1 FOREIGN KEY (LAYERS_ID) REFERENCES LAYERS (ID) ON DELETE CASCADE ON UPDATE CASCADE;
CREATE INDEX LAYERS_SEMANTIC_IDX1 ON LAYERS_SEMANTIC (OBJECT_ID);
/* Privileges of users */
GRANT ALL ON LAYERS_SEMANTIC TO PUBLIC;
CREATE GENERATOR LAYERS_SEMANTIC_GEN;
