CREATE TABLE SQL_QUERIES (
    ID INTEGER,
    NAME VARCHAR(50),
    SQL_TEXT BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    COMMENT BLOB SUB_TYPE 1 SEGMENT SIZE 80);

INSERT INTO SQL_QUERIES (ID, NAME, SQL_TEXT, COMMENT)
                 VALUES (1, 'SQL_GET_LOTS', 'SELECT
    A.ID, A.ADDRESS, A.DOC_NUMBER, A.DOC_DATE, A.AREA, A.EXECUTOR, A.VRS, A.CREATOR, AC.ID AS CNT_ID, AC.CNT_POSITIVE, AC.CNT_ENABLED, AP.ID AS PT_AD, AP.CONTOURS_ID, AP.X, AP.Y, AP.PT_NAME
FROM
    ALLOTMENTS A
    LEFT JOIN
    ALLOTMENT_CONTOURS AC ON (A.ID = AC.ALLOTMENTS_ID)
    LEFT JOIN ALLOTMENT_POINTS AP ON (A.ID = AP.ALLOTMENTS_ID AND AC.ID = AP.CONTOURS_ID)
WHERE
    (A.MINX < 300000) AND (A.MINY < 300000) AND
    (NOT(
            (:XMAX <= A.MINX)
            OR
            (A.MAXX <= :XMIN)
            OR
            (:YMAX <= A.MINY)
            OR
            (A.MAXY <= :YMIN)
        )
    )
    AND
    (A.CHECKED = :CHECKED)
    AND
    (A.CANCELLED = :CANCELLED)
ORDER BY
  A.ID, AC.ID, AP.ID', NULL);
INSERT INTO SQL_QUERIES (ID, NAME, SQL_TEXT, COMMENT)
                 VALUES (4, 'GET_LOTS_COUNT_NO_CATEGORY', 'SELECT
    COUNT(ID)
FROM
    ALLOTMENTS
WHERE
    (NOT((:XMAX < MINX) OR (MAXX < :XMIN) OR (:YMAX < MINY) OR (MAXY < :YMIN)))
    AND
    (LOT_KINDS_ID IS NULL)
    AND
    (CHECKED = :CHECKED)
    AND
    (CANCELLED = :CANCELLED)', '„исло отводов без категории.');
INSERT INTO SQL_QUERIES (ID, NAME, SQL_TEXT, COMMENT)
                 VALUES (2, 'GET_LOTS_XY_COUNT_WITH_KIND', 'SELECT
    COUNT(AP.ID)
FROM
    ALLOTMENTS A
    LEFT JOIN
    ALLOTMENT_CONTOURS AC ON (A.ID = AC.ALLOTMENTS_ID)
    LEFT JOIN ALLOTMENT_POINTS AP ON (A.ID = AP.ALLOTMENTS_ID AND AC.ID = AP.CONTOURS_ID)
WHERE
    ((A.MINX < 300000) AND (A.MINY < 300000))
    AND
    (NOT( (:XMAX <= A.MINX) OR (A.MAXX <= :XMIN) or (:YMAX <= A.MINY) OR (A.MAXY <= :YMIN) )
    AND
    (A.LOT_KINDS_ID = :LOT_KINDS_ID)', ' оличество точек дл€ загрузки отводов выбранной категории');
INSERT INTO SQL_QUERIES (ID, NAME, SQL_TEXT, COMMENT)
                 VALUES (3, 'GET_LOTS_XY_WITH_KIND', 'SELECT
    A.ID, A.ADDRESS, A.DOC_NUMBER, A.DOC_DATE, A.AREA, A.EXECUTOR, A.VRS, A.CREATOR,
    AC.ID AS CNT_ID, AC.CNT_POSITIVE, AC.CNT_ENABLED,
    AP.ID AS PT_ID, AP.CONTOURS_ID AP.X, AP.Y, AP.PT_NAME
FROM
    ALLOTMENTS A
    LEFT JOIN
    ALLOTMENT_CONTOURS AC ON (A.ID = AC.ALLOTMENTS_ID)
    LEFT JOIN ALLOTMENT_POINTS AP ON (A.ID = AP.ALLOTMENTS_ID AND AC.ID = AP.CONTOURS_ID)
WHERE
    ((A.MINX < 300000) AND (A.MINY < 300000))
    AND
    (NOT( (:XMAX <= A.MINX) OR (A.MAXX <= :XMIN) or (:YMAX <= A.MINY) OR (A.MAXY <= :YMIN) )
    AND
    (A.LOT_KINDS_ID = :LOT_KINDS_ID)
ORDER BY
  A.ID, AC.ID, AP.ID', '“очки дл€ загрузки отводов выбранной категории');
INSERT INTO SQL_QUERIES (ID, NAME, SQL_TEXT, COMMENT)
                 VALUES (5, 'GET_LOTS_NO_CATEGORY', 'SELECT
    ID, ADDRESS, DOC_NUMBER, DOC_DATE, AREA, EXECUTOR, VRS, CREATOR, LOT_KINDS_ID
FROM
    ALLOTMENTS
WHERE
    (NOT((:XMAX < MINX) OR (MAXX < :XMIN) OR (:YMAX < MINY) OR (MAXY < :YMIN)))
    AND
    (LOT_KINDS_ID IS NULL)
    AND
    (CHECKED = :CHECKED)
    AND
    (CANCELLED = :CANCELLED)', 'ќтводы без категории.');
INSERT INTO SQL_QUERIES (ID, NAME, SQL_TEXT, COMMENT)
                 VALUES (6, 'GET_LOT_CONTOURS', 'SELECT * FROM ALLOTMENT_CONTOURS WHERE ALLOTMENTS_ID=:ID ORDER BY ID', NULL);
INSERT INTO SQL_QUERIES (ID, NAME, SQL_TEXT, COMMENT)
                 VALUES (7, 'GET_LOT_POINTS', 'SELECT * FROM ALLOTMENT_POINTS WHERE ALLOTMENTS_ID=:ID ORDER BY CONTOURS_ID, ID', NULL);
INSERT INTO SQL_QUERIES (ID, NAME, SQL_TEXT, COMMENT)
                 VALUES (8, 'GET_LOTS_COUNT_WITH_CATEGORY', 'SELECT
    COUNT(ID)
FROM
    ALLOTMENTS
WHERE
    (NOT((:XMAX < MINX) OR (MAXX < :XMIN) OR (:YMAX < MINY) OR (MAXY < :YMIN)))
    AND
    (LOT_KINDS_ID = :LOT_KINDS_ID)', NULL);
INSERT INTO SQL_QUERIES (ID, NAME, SQL_TEXT, COMMENT)
                 VALUES (9, 'GET_LOTS_WITH_CATEGORY', 'SELECT
    ID, ADDRESS, DOC_NUMBER, DOC_DATE, AREA, EXECUTOR, VRS, CREATOR, LOT_KINDS_ID
FROM
    ALLOTMENTS
WHERE
    (NOT((:XMAX < MINX) OR (MAXX < :XMIN) OR (:YMAX < MINY) OR (MAXY < :YMIN)))
    AND
    (LOT_KINDS_ID = :LOT_KINDS_ID)', NULL);
INSERT INTO SQL_QUERIES (ID, NAME, SQL_TEXT, COMMENT)
                 VALUES (10, 'GET_ALLOTMENT_MAIN_DATA', 'SELECT ID, ADDRESS, DOC_NUMBER, DOC_DATE, AREA, EXECUTOR, CHECKED, CANCELLED, VRS, LOT_KINDS_ID
FROM ALLOTMENTS WHERE ID=:ID', NULL);

COMMIT WORK;

ALTER TABLE ALLOTMENT_CONTOURS
ADD CLOSED IBBOOL
NOT NULL 

UPDATE ALLOTMENT_CONTOURS
SET CLOSED=1



ALTER TABLE ALLOTMENT_CONTOURS
ADD NAME STRING255;

ALTER TABLE ALLOTMENT_CONTOURS
ADD COLOR INTEGER


ALTER TABLE ALLOTMENTS
ADD LINK_CONSULTANT STRING1000;

COMMIT WORK;
