ALTER TABLE PEOPLE
ADD CAN_SEE_ALL_OFFICES IBBOOL
NOT NULL;

UPDATE PEOPLE
SET CAN_SEE_ALL_OFFICES = 0;

ALTER TABLE LETTERS_ORDERS
ADD KIND SMALLINT;

UPDATE LETTERS_ORDERS
SET KIND = 0;

SET TERM ^ ;

CREATE OR ALTER procedure UPDATE_LETTERS_ORDERS_BY_OFDOCS (
    OFF_DOC_ID integer,
    LETTER_ID integer)
as
begin
  DELETE FROM LETTERS_ORDERS WHERE LETTERS_ID=:LETTER_ID AND KIND <> 1;
  INSERT INTO letters_orders (LETTERS_ID, ORDERS_ID, KIND)
  SELECT :LETTER_ID, id, 0 FROM ORDERS WHERE OFFICE_DOCS_ID=:OFF_DOC_ID;
end^

SET TERM ; ^


SET TERM ^ ;

CREATE OR ALTER procedure UPDATE_LETTERS_ORDERS_BY_ORDERS (
    ORDER_ID integer,
    OFF_DOC_ID integer)
as
begin
  DELETE FROM LETTERS_ORDERS WHERE ORDERS_ID=:ORDER_ID AND KIND <> 1;
  INSERT INTO LETTERS_ORDERS (LETTERS_ID, ORDERS_ID, KIND)
  SELECT LAST_LETTERS_ID, :ORDER_ID, 0 FROM OFFICE_DOCS WHERE ID=:OFF_DOC_ID;
end^

SET TERM ; ^

SET TERM ^ ;

CREATE OR ALTER TRIGGER OFFICE_DOC_LETTERS_AD0 FOR OFFICE_DOC_LETTERS
ACTIVE AFTER DELETE POSITION 0
AS
begin
  DELETE FROM LETTERS_ORDERS WHERE LETTERS_ID=OLD.LETTERS_ID AND KIND = 0;
end^

SET TERM ; ^

SET TERM ^ ;

SET TERM ^ ;

CREATE OR ALTER procedure SAVE_ORDER2 (
    ID integer,
    OFFICES_ID integer,
    DOC_NUMBER varchar(10),
    DOC_DATE date,
    ORDER_NUMBER varchar(10),
    ORDER_DATE date,
    CONTRAGENTS_ID integer,
    NDS numeric(5,2),
    SUMMA numeric(9,2),
    SUM_NDS numeric(9,2),
    CHECKED smallint,
    PAY_DATE date,
    EXECUTOR varchar(50),
    ACT_DATE date,
    CONTRACT_NUMBER varchar(10),
    OBJECT_ADDRESS varchar(120),
    CUSTOMER varchar(500),
    VAL_PERIOD smallint,
    TICKET varchar(10),
    INFORMATION varchar(20),
    MARK_EXECUTOR smallint,
    SUM_BASE numeric(9,2),
    CANCELLED smallint,
    PEOPLE_ID integer,
    PAYER_ID integer,
    PAYER_CUSTOMER varchar(500),
    CUSTOMER_BASE varchar(255),
    PRINT_WORKS_VALUE smallint,
    PAYER_ACCOUNT varchar(20),
    PAYER_BANK_ID integer,
    PAYER_ACCOUNT_TYPE smallint,
    OFFICE_DOCS_ID integer,
    CLOSED smallint,
    LETTERS_ID integer)
as
BEGIN
  IF (EXISTS(SELECT ID FROM ORDERS WHERE (ID = :ID))) THEN
    UPDATE ORDERS
    SET OFFICES_ID = :OFFICES_ID,
        DOC_NUMBER = :DOC_NUMBER,
        DOC_DATE = :DOC_DATE,
        ORDER_NUMBER = :ORDER_NUMBER,
        ORDER_DATE = :ORDER_DATE,
        CONTRAGENTS_ID = :CONTRAGENTS_ID,
        NDS = :NDS,
        SUMMA = :SUMMA,
        SUM_NDS = :SUM_NDS,
        CHECKED = :CHECKED,
        PAY_DATE = :PAY_DATE,
        EXECUTOR = :EXECUTOR,
        ACT_DATE = :ACT_DATE,
        CONTRACT_NUMBER = :CONTRACT_NUMBER,
        OBJECT_ADDRESS = :OBJECT_ADDRESS,
        CUSTOMER = :CUSTOMER,
        CUSTOMER_BASE = :CUSTOMER_BASE,
        VAL_PERIOD = :VAL_PERIOD,
        TICKET = :TICKET,
        INFORMATION = :INFORMATION,
        MARK_EXECUTOR = :MARK_EXECUTOR,
        SUM_BASE = :SUM_BASE,
        CANCELLED = :CANCELLED,
        PEOPLE_ID = :PEOPLE_ID,
        PAYER_ID = :PAYER_ID,
        PAYER_CUSTOMER = :PAYER_CUSTOMER,
        PRINT_WORKS_VALUE = :PRINT_WORKS_VALUE,
        PAYER_ACCOUNT = :PAYER_ACCOUNT,
        PAYER_BANK_ID = :PAYER_BANK_ID,
        PAYER_ACCOUNT_TYPE = :PAYER_ACCOUNT_TYPE,
        OFFICE_DOCS_ID = :OFFICE_DOCS_ID,
        CLOSED = :CLOSED
    WHERE (ID = :ID);
  ELSE
    INSERT INTO ORDERS (
        ID,
        OFFICES_ID,
        DOC_NUMBER,
        DOC_DATE,
        ORDER_NUMBER,
        ORDER_DATE,
        CONTRAGENTS_ID,
        NDS,
        SUMMA,
        SUM_NDS,
        CHECKED,
        PAY_DATE,
        EXECUTOR,
        ACT_DATE,
        CONTRACT_NUMBER,
        OBJECT_ADDRESS,
        CUSTOMER,
        CUSTOMER_BASE,
        VAL_PERIOD,
        TICKET,
        INFORMATION,
        MARK_EXECUTOR,
        SUM_BASE,
        CANCELLED,
        PEOPLE_ID,
        PAYER_ID,
        PAYER_CUSTOMER,
        PRINT_WORKS_VALUE,
        PAYER_ACCOUNT,
        PAYER_BANK_ID,
        PAYER_ACCOUNT_TYPE,
        OFFICE_DOCS_ID,
        CLOSED)
    VALUES (
        :ID,
        :OFFICES_ID,
        :DOC_NUMBER,
        :DOC_DATE,
        :ORDER_NUMBER,
        :ORDER_DATE,
        :CONTRAGENTS_ID,
        :NDS,
        :SUMMA,
        :SUM_NDS,
        :CHECKED,
        :PAY_DATE,
        :EXECUTOR,
        :ACT_DATE,
        :CONTRACT_NUMBER,
        :OBJECT_ADDRESS,
        :CUSTOMER,
        :CUSTOMER_BASE,
        :VAL_PERIOD,
        :TICKET,
        :INFORMATION,
        :MARK_EXECUTOR,
        :SUM_BASE,
        :CANCELLED,
        :PEOPLE_ID,
        :PAYER_ID,
        :PAYER_CUSTOMER,
        :PRINT_WORKS_VALUE,
        :PAYER_ACCOUNT,
        :PAYER_BANK_ID,
        :PAYER_ACCOUNT_TYPE,
        :OFFICE_DOCS_ID,
        :CLOSED);
  /* Удаляем ссылку на входящее письмо, заданное пользователем */
  DELETE FROM LETTERS_ORDERS WHERE ORDERS_ID = :ID AND KIND = 1;
  /* Добавляем новую ссылку на входящее письмо, заданное пользователем */
  IF (NOT (:LETTERS_ID IS NULL)) THEN
    IF (NOT EXISTS(SELECT LETTERS_ID FROM LETTERS_ORDERS WHERE (ORDERS_ID = :ID) AND (LETTERS_ID = :LETTERS_ID))) THEN
        INSERT INTO LETTERS_ORDERS (LETTERS_ID, ORDERS_ID, KIND)
        VALUES (:LETTERS_ID, :ID, 1);
END^

SET TERM ; ^

DECLARE EXTERNAL FUNCTION addDay
   TIMESTAMP, INT
   RETURNS TIMESTAMP
   ENTRY_POINT 'addDay' MODULE_NAME 'fbudf';

SET TERM ^ ;

CREATE OR ALTER PROCEDURE SAVE_ORDER2 (
    ID INTEGER,
    OFFICES_ID INTEGER,
    DOC_NUMBER VARCHAR(10),
    DOC_DATE DATE,
    ORDER_NUMBER VARCHAR(10),
    ORDER_DATE DATE,
    CONTRAGENTS_ID INTEGER,
    NDS NUMERIC(5,2),
    SUMMA NUMERIC(9,2),
    SUM_NDS NUMERIC(9,2),
    CHECKED SMALLINT,
    PAY_DATE DATE,
    EXECUTOR VARCHAR(50),
    ACT_DATE DATE,
    CONTRACT_NUMBER VARCHAR(10),
    OBJECT_ADDRESS VARCHAR(120),
    CUSTOMER VARCHAR(500),
    VAL_PERIOD SMALLINT,
    TICKET VARCHAR(10),
    INFORMATION VARCHAR(20),
    MARK_EXECUTOR SMALLINT,
    SUM_BASE NUMERIC(9,2),
    CANCELLED SMALLINT,
    PEOPLE_ID INTEGER,
    PAYER_ID INTEGER,
    PAYER_CUSTOMER VARCHAR(500),
    CUSTOMER_BASE VARCHAR(255),
    PRINT_WORKS_VALUE SMALLINT,
    PAYER_ACCOUNT VARCHAR(20),
    PAYER_BANK_ID INTEGER,
    PAYER_ACCOUNT_TYPE SMALLINT,
    OFFICE_DOCS_ID INTEGER,
    CLOSED SMALLINT,
    LETTERS_ID INTEGER)
AS
DECLARE VARIABLE L_ID INTEGER;
DECLARE VARIABLE L_CD2 DATE;
DECLARE VARIABLE L_NEW_CD2 DATE;
DECLARE VARIABLE L_MIN_CD2 DATE;
BEGIN
  IF (EXISTS(SELECT ID FROM ORDERS WHERE (ID = :ID))) THEN
    UPDATE ORDERS
    SET OFFICES_ID = :OFFICES_ID,
        DOC_NUMBER = :DOC_NUMBER,
        DOC_DATE = :DOC_DATE,
        ORDER_NUMBER = :ORDER_NUMBER,
        ORDER_DATE = :ORDER_DATE,
        CONTRAGENTS_ID = :CONTRAGENTS_ID,
        NDS = :NDS,
        SUMMA = :SUMMA,
        SUM_NDS = :SUM_NDS,
        CHECKED = :CHECKED,
        PAY_DATE = :PAY_DATE,
        EXECUTOR = :EXECUTOR,
        ACT_DATE = :ACT_DATE,
        CONTRACT_NUMBER = :CONTRACT_NUMBER,
        OBJECT_ADDRESS = :OBJECT_ADDRESS,
        CUSTOMER = :CUSTOMER,
        CUSTOMER_BASE = :CUSTOMER_BASE,
        VAL_PERIOD = :VAL_PERIOD,
        TICKET = :TICKET,
        INFORMATION = :INFORMATION,
        MARK_EXECUTOR = :MARK_EXECUTOR,
        SUM_BASE = :SUM_BASE,
        CANCELLED = :CANCELLED,
        PEOPLE_ID = :PEOPLE_ID,
        PAYER_ID = :PAYER_ID,
        PAYER_CUSTOMER = :PAYER_CUSTOMER,
        PRINT_WORKS_VALUE = :PRINT_WORKS_VALUE,
        PAYER_ACCOUNT = :PAYER_ACCOUNT,
        PAYER_BANK_ID = :PAYER_BANK_ID,
        PAYER_ACCOUNT_TYPE = :PAYER_ACCOUNT_TYPE,
        OFFICE_DOCS_ID = :OFFICE_DOCS_ID,
        CLOSED = :CLOSED
    WHERE (ID = :ID);
  ELSE
    INSERT INTO ORDERS (
        ID,
        OFFICES_ID,
        DOC_NUMBER,
        DOC_DATE,
        ORDER_NUMBER,
        ORDER_DATE,
        CONTRAGENTS_ID,
        NDS,
        SUMMA,
        SUM_NDS,
        CHECKED,
        PAY_DATE,
        EXECUTOR,
        ACT_DATE,
        CONTRACT_NUMBER,
        OBJECT_ADDRESS,
        CUSTOMER,
        CUSTOMER_BASE,
        VAL_PERIOD,
        TICKET,
        INFORMATION,
        MARK_EXECUTOR,
        SUM_BASE,
        CANCELLED,
        PEOPLE_ID,
        PAYER_ID,
        PAYER_CUSTOMER,
        PRINT_WORKS_VALUE,
        PAYER_ACCOUNT,
        PAYER_BANK_ID,
        PAYER_ACCOUNT_TYPE,
        OFFICE_DOCS_ID,
        CLOSED)
    VALUES (
        :ID,
        :OFFICES_ID,
        :DOC_NUMBER,
        :DOC_DATE,
        :ORDER_NUMBER,
        :ORDER_DATE,
        :CONTRAGENTS_ID,
        :NDS,
        :SUMMA,
        :SUM_NDS,
        :CHECKED,
        :PAY_DATE,
        :EXECUTOR,
        :ACT_DATE,
        :CONTRACT_NUMBER,
        :OBJECT_ADDRESS,
        :CUSTOMER,
        :CUSTOMER_BASE,
        :VAL_PERIOD,
        :TICKET,
        :INFORMATION,
        :MARK_EXECUTOR,
        :SUM_BASE,
        :CANCELLED,
        :PEOPLE_ID,
        :PAYER_ID,
        :PAYER_CUSTOMER,
        :PRINT_WORKS_VALUE,
        :PAYER_ACCOUNT,
        :PAYER_BANK_ID,
        :PAYER_ACCOUNT_TYPE,
        :OFFICE_DOCS_ID,
        :CLOSED);
  /* Удаляем старую ссылку на входящее письмо, заданное пользователем */
  DELETE FROM LETTERS_ORDERS WHERE ORDERS_ID = :ID AND KIND = 1;
  /* Вставляем новую ссылку на входящее письмо, заданное пользователем */
  IF (NOT (:LETTERS_ID IS NULL)) THEN
    IF (NOT EXISTS(SELECT LETTERS_ID FROM LETTERS_ORDERS WHERE (ORDERS_ID = :ID) AND (LETTERS_ID = :LETTERS_ID))) THEN
        INSERT INTO LETTERS_ORDERS (LETTERS_ID, ORDERS_ID, KIND)
        VALUES (:LETTERS_ID, :ID, 1);
  /* Обновляем контрольную дату письма */
  IF (NOT (:PAY_DATE IS NULL)) THEN
    IF (NOT (:VAL_PERIOD IS NULL)) THEN
    IF (NOT (:LETTERS_ID IS NULL)) THEN
    BEGIN
      SELECT LETTERS.ID, LETTERS.CONTROL_DATE_2
      FROM LETTERS
      WHERE LETTERS.ID=:LETTERS_ID
      INTO :L_ID, :L_CD2;

      IF (NOT (:L_ID IS NULL)) THEN
      BEGIN
        SELECT ADDDAY(:PAY_DATE, :VAL_PERIOD)
        FROM RDB$DATABASE
        INTO :L_NEW_CD2;

        SELECT MIN(ADDDAY(PAY_DATE, VAL_PERIOD))
        FROM ORDERS, LETTERS_ORDERS
        WHERE ORDERS.ID=LETTERS_ORDERS.ORDERS_ID AND LETTERS_ORDERS.LETTERS_ID=:L_ID
        INTO :L_MIN_CD2;

        if (:L_MIN_CD2 < :L_NEW_CD2) then
          L_NEW_CD2=L_MIN_CD2;

        if ((:L_CD2 IS NULL) or (:L_CD2 > :L_NEW_CD2) ) then
        BEGIN
          UPDATE LETTERS
          SET LETTERS.CONTROL_DATE_2 = :L_NEW_CD2
          WHERE LETTERS.ID=:LETTERS_ID;
        END
      END
    END
END^

SET TERM ; ^













