ALTER TABLE PEOPLE
ADD CAN_CREATE_ORDERS IBBOOL;

UPDATE PEOPLE
SET CAN_CREATE_ORDERS = 0;

update RDB$RELATION_FIELDS
set RDB$DESCRIPTION = '„еловек может создавать и редактировать заказы.'
where (RDB$RELATION_NAME = 'PEOPLE') and
(RDB$FIELD_NAME = 'CAN_CREATE_ORDERS');

