CREATE TABLE MAP_SCANS (
    ID ID NOT NULL,
    NOMENCLATURE STRING20 NOT NULL,
    START_DATE DATE NOT NULL,
    IS_SECRET IBBOOL);

ALTER TABLE MAP_SCANS ADD CONSTRAINT PK_MAP_SCANS PRIMARY KEY (ID);

CREATE TABLE MAP_SCANS_GIVEOUTS (
    ID                  INTEGER NOT NULL,
    MAP_SCANS_ID        INTEGER NOT NULL,
    DATE_OF_BACK        DATE,
    DATE_OF_GIVE        DATE NOT NULL,
    DEFINITION_NUMBER   STRING10 COLLATE PXW_CYRL /* STRING10 = VARCHAR(10) */,
    GIVEN_OBJECT        IBBOOL NOT NULL /* IBBOOL = SMALLINT DEFAULT 0 NOT NULL CHECK (VALUE IN (0, 1)) */,
    HOLDER              IBBOOL NOT NULL /* IBBOOL = SMALLINT DEFAULT 0 NOT NULL CHECK (VALUE IN (0, 1)) */,
    HOLDER_NAME         STRING300 COLLATE PXW_CYRL /* STRING300 = VARCHAR(300) DEFAULT '' */,
    ORDER_NUMBER        NUMBER_CHAR COLLATE PXW_CYRL /* NUMBER_CHAR = VARCHAR(12) */,
    ORDERS_ID           INTEGER,
    LICENSED_ORGS_ID    INTEGER,
    PEOPLE_ID           INTEGER,
    PERSON_WHO_GIVE_ID  INTEGER,
    TERM_OF_GIVE        INTEGER NOT NULL,
    ADDRESS             VARCHAR(400),
    OFFICES_ID          INTEGER,
    EXPIRED             COMPUTED BY ((CASE WHEN (DATE_OF_BACK IS NULL) AND ((DATE_OF_GIVE + TERM_OF_GIVE) < CURRENT_DATE) THEN 1 ELSE 0 END)),
    STATUS              COMPUTED BY ((CASE WHEN (DATE_OF_BACK IS NULL) THEN 1 ELSE 0 END)),
    PEOPLE_NAME         STRING100 COLLATE PXW_CYRL /* STRING100 = VARCHAR(100) */,
    MD5_OLD             STRING50,
    MD5_NEW             STRING50,
    ACTUAL_MD5          COMPUTED BY ((CASE WHEN ((MD5_NEW IS NULL) or (MD5_NEW = ''))  THEN MD5_OLD ELSE MD5_NEW END))
);

ALTER TABLE MAP_SCANS_GIVEOUTS
  ADD CONSTRAINT PK_MAP_SCANS_GIVEOUTS PRIMARY KEY (ID);
ALTER TABLE MAP_SCANS_GIVEOUTS
    ADD CONSTRAINT FK_MAP_SCANS_GIVEOUTS_1
    FOREIGN KEY (MAP_SCANS_ID)
    REFERENCES MAP_SCANS(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

ALTER TABLE MAP_SCANS
  ADD LAST_GIVE_ID
  COMPUTED BY ((SELECT  MAX(MSG.ID) FROM MAP_SCANS_GIVEOUTS MSG WHERE MSG.MAP_SCANS_ID = MAP_SCANS.ID));
ALTER TABLE MAP_SCANS
  ADD EXPIRED
  COMPUTED BY ((SELECT EXPIRED FROM MAP_SCANS_GIVEOUTS MSG WHERE MSG.ID = MAP_SCANS.LAST_GIVE_ID));
ALTER TABLE MAP_SCANS
  ADD GIVE_STATUS
  COMPUTED BY ((SELECT STATUS FROM MAP_SCANS_GIVEOUTS MSG WHERE MSG.ID = MAP_SCANS.LAST_GIVE_ID));
ALTER TABLE MAP_SCANS
  ADD HOLDER_NAME
  COMPUTED BY ((CASE GIVE_STATUS WHEN 1 THEN (SELECT HOLDER_NAME FROM MAP_SCANS_GIVEOUTS MSG WHERE MSG.ID = MAP_SCANS.LAST_GIVE_ID) WHEN 0 THEN '' END ));
ALTER TABLE MAP_SCANS
  ADD DATE_OF_GIVE
  COMPUTED BY ((CASE GIVE_STATUS WHEN 1 THEN (SELECT DATE_OF_GIVE FROM MAP_SCANS_GIVEOUTS MSG WHERE MSG.ID = MAP_SCANS.LAST_GIVE_ID) WHEN 0 THEN NULL END));
ALTER TABLE MAP_SCANS
  ADD ACTUAL_MD5
  COMPUTED BY ((SELECT MSG.ACTUAL_MD5 FROM MAP_SCANS_GIVEOUTS MSG WHERE MSG.ID = MAP_SCANS.LAST_GIVE_ID));

SET TERM ^ ;

CREATE OR ALTER PROCEDURE SAVE_MAP_SCAN (
    ID INTEGER,
    NOMENCLATURE VARCHAR(20),
    START_DATE DATE,
    IS_SECRET SMALLINT)
AS
BEGIN
  IF (EXISTS(SELECT ID FROM MAP_SCANS WHERE (ID = :ID))) THEN
    UPDATE MAP_SCANS
    SET NOMENCLATURE = :NOMENCLATURE,
        START_DATE = :START_DATE,
        IS_SECRET = :IS_SECRET
    WHERE (ID = :ID);
  ELSE
    INSERT INTO MAP_SCANS (
        ID,
        NOMENCLATURE,
        START_DATE,
        IS_SECRET)
    VALUES (
        :ID,
        :NOMENCLATURE,
        :START_DATE,
        :IS_SECRET);
END^

SET TERM ; ^

GRANT SELECT,INSERT,UPDATE ON MAP_SCANS TO PROCEDURE SAVE_MAP_SCAN;
GRANT EXECUTE ON PROCEDURE SAVE_MAP_SCAN TO PUBLIC;

SET TERM ^ ;

CREATE OR ALTER PROCEDURE SAVE_MAP_SCAN_GIVEOUT (
    ID INTEGER,
    MAP_SCANS_ID INTEGER,
    DATE_OF_BACK DATE,
    DATE_OF_GIVE DATE,
    DEFINITION_NUMBER VARCHAR(10),
    GIVEN_OBJECT SMALLINT,
    HOLDER SMALLINT,
    HOLDER_NAME VARCHAR(300),
    ORDER_NUMBER VARCHAR(10),
    ORDERS_ID INTEGER,
    LICENSED_ORGS_ID INTEGER,
    PEOPLE_ID INTEGER,
    PERSON_WHO_GIVE_ID INTEGER,
    TERM_OF_GIVE INTEGER,
    ADDRESS VARCHAR(400),
    OFFICES_ID INTEGER,
    MD5_OLD VARCHAR(50),
    MD5_NEW VARCHAR(50))
AS
BEGIN
  IF (EXISTS(SELECT ID FROM MAP_SCANS_GIVEOUTS WHERE (ID = :ID))) THEN
    UPDATE MAP_SCANS_GIVEOUTS
    SET MAP_SCANS_ID = :MAP_SCANS_ID,
        DATE_OF_BACK = :DATE_OF_BACK,
        DATE_OF_GIVE = :DATE_OF_GIVE,
        DEFINITION_NUMBER = :DEFINITION_NUMBER,
        GIVEN_OBJECT = :GIVEN_OBJECT,
        HOLDER = :HOLDER,
        HOLDER_NAME = :HOLDER_NAME,
        ORDER_NUMBER = :ORDER_NUMBER,
        ORDERS_ID = :ORDERS_ID,
        LICENSED_ORGS_ID = :LICENSED_ORGS_ID,
        PEOPLE_ID = :PEOPLE_ID,
        PERSON_WHO_GIVE_ID = :PERSON_WHO_GIVE_ID,
        TERM_OF_GIVE = :TERM_OF_GIVE,
        ADDRESS = :ADDRESS,
        OFFICES_ID = :OFFICES_ID,
        MD5_OLD = :MD5_OLD,
        MD5_NEW = :MD5_NEW
    WHERE (ID = :ID);
  ELSE
    INSERT INTO MAP_SCANS_GIVEOUTS (
        ID,
        MAP_SCANS_ID,
        DATE_OF_BACK,
        DATE_OF_GIVE,
        DEFINITION_NUMBER,
        GIVEN_OBJECT,
        HOLDER,
        HOLDER_NAME,
        ORDER_NUMBER,
        ORDERS_ID,
        LICENSED_ORGS_ID,
        PEOPLE_ID,
        PERSON_WHO_GIVE_ID,
        TERM_OF_GIVE,
        ADDRESS,
        OFFICES_ID,
        MD5_OLD,
        MD5_NEW
        )
    VALUES (
        :ID,
        :MAP_SCANS_ID,
        :DATE_OF_BACK,
        :DATE_OF_GIVE,
        :DEFINITION_NUMBER,
        :GIVEN_OBJECT,
        :HOLDER,
        :HOLDER_NAME,
        :ORDER_NUMBER,
        :ORDERS_ID,
        :LICENSED_ORGS_ID,
        :PEOPLE_ID,
        :PERSON_WHO_GIVE_ID,
        :TERM_OF_GIVE,
        :ADDRESS,
        :OFFICES_ID,
        :MD5_OLD,
        :MD5_NEW
        );
END^

SET TERM ; ^

GRANT SELECT,INSERT,UPDATE,DELETE ON MAP_SCANS TO PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON MAP_SCANS_GIVEOUTS TO PUBLIC;
GRANT SELECT,INSERT,UPDATE ON MAP_SCANS_GIVEOUTS TO PROCEDURE SAVE_MAP_SCAN_GIVEOUT;
GRANT EXECUTE ON PROCEDURE SAVE_MAP_SCAN_GIVEOUT TO PUBLIC;
GRANT SELECT,INSERT,UPDATE ON MAP_SCANS TO PROCEDURE SAVE_MAP_SCAN;
GRANT EXECUTE ON PROCEDURE SAVE_MAP_SCAN TO PUBLIC;

CREATE GENERATOR MAP_SCANS_GEN;
CREATE GENERATOR MAP_SCANS_GIVEOUTS_GEN;
