SET SQL DIALECT 3;

CREATE GENERATOR SCAN_ORDERS_GEN;
CREATE GENERATOR SCAN_ORDER_MAPS_GEN;

CREATE TABLE SCAN_ORDERS (
    ID            ID NOT NULL /* ID = INTEGER DEFAULT 0 NOT NULL */,
    ORDER_DATE    DATE NOT NULL,
    ORDER_NUMBER  NUMBER_CHAR NOT NULL /* NUMBER_CHAR = VARCHAR(12) */,
    YEAR_NUMBER   COMPUTED BY (CAST(EXTRACT(YEAR FROM ORDER_DATE) AS VARCHAR(4)) || '/' || ORDER_NUMBER),
    ADDRESS       STRING1000 /* STRING1000 = VARCHAR(1000) */,
    WORK_TYPE     STRING1000 /* STRING1000 = VARCHAR(1000) */,
    OFFICES_ID    INTEGER,
    LICENSED_ORGS_ID INTEGER
);
ALTER TABLE SCAN_ORDERS ADD CONSTRAINT PK_SCAN_ORDERS PRIMARY KEY (ID);
CREATE INDEX SCAN_ORDERS_IDX1 ON SCAN_ORDERS (ORDER_DATE);
CREATE INDEX SCAN_ORDERS_IDX2 ON SCAN_ORDERS (ORDER_NUMBER);
INSERT INTO SCAN_ORDERS (ID, ORDER_DATE, ORDER_NUMBER, ADDRESS, WORK_TYPE)
VALUES (0, CURRENT_DATE, '0', 'мер', '');
INSERT INTO LICENSED_ORGS (ID) VALUES (0);
ALTER TABLE SCAN_ORDERS ADD CONSTRAINT FK_SCAN_ORDERS_1 FOREIGN KEY (OFFICES_ID) REFERENCES OFFICES (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE SCAN_ORDERS ADD CONSTRAINT FK_SCAN_ORDERS_2 FOREIGN KEY (LICENSED_ORGS_ID) REFERENCES LICENSED_ORGS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE SCAN_ORDER_MAPS (
    ID              ID NOT NULL /* ID = INTEGER DEFAULT 0 NOT NULL */,
    SCAN_ORDERS_ID  ID /* ID = INTEGER DEFAULT 0 NOT NULL */,
    NOMENCLATURE    STRING20 NOT NULL /* STRING20 = VARCHAR(20) */
);
ALTER TABLE SCAN_ORDER_MAPS ADD CONSTRAINT PK_SCAN_ORDER_MAPS PRIMARY KEY (ID);
ALTER TABLE SCAN_ORDER_MAPS ADD CONSTRAINT FK_SCAN_ORDER_MAPS_1 FOREIGN KEY (SCAN_ORDERS_ID) REFERENCES SCAN_ORDERS (ID) ON DELETE CASCADE ON UPDATE CASCADE;
CREATE INDEX SCAN_ORDER_MAPS_IDX1 ON SCAN_ORDER_MAPS (NOMENCLATURE);

ALTER TABLE MAP_SCANS_GIVEOUTS
ADD SCAN_ORDER_MAPS_ID INTEGER;
ALTER TABLE MAP_SCANS_GIVEOUTS
ADD CONSTRAINT FK_MAP_SCANS_GIVEOUTS_3
FOREIGN KEY (SCAN_ORDER_MAPS_ID)
REFERENCES SCAN_ORDERS(ID);

CREATE VIEW SCAN_ORDER_MAP_STATE(
    ID,
    SCAN_ORDERS_ID,
    NOMENCLATURE,
    GIVEOUT_ID,
    GIVEDOUT,
    RETURNED)
AS
SELECT SOM.ID, SOM.SCAN_ORDERS_ID, SOM.NOMENCLATURE, MSG.ID AS GIVEOUT_ID,
 CASE WHEN MSG.ID IS NULL THEN 0 ELSE 1 END AS GIVEDOUT,
 CASE WHEN MSG.DATE_OF_BACK IS NULL THEN 0 ELSE 1 END AS RETURNED
FROM SCAN_ORDER_MAPS SOM
     LEFT JOIN MAP_SCANS_GIVEOUTS MSG ON (SOM.ID=MSG.SCAN_ORDER_MAPS_ID)
;

GRANT SELECT ON MAP_SCANS TO VIEW SCAN_ORDER_MAP_STATE;
GRANT SELECT ON MAP_SCANS_GIVEOUTS TO VIEW SCAN_ORDER_MAP_STATE;
GRANT SELECT ON SCAN_ORDER_MAPS TO VIEW SCAN_ORDER_MAP_STATE;
GRANT SELECT ON SCAN_ORDER_MAP_STATE TO VIEW SCAN_ORDERS_ALL_VIEW;
GRANT SELECT ON SCAN_ORDER_MAP_STATE TO ADMINISTRATOR;
GRANT SELECT ON SCAN_ORDER_MAP_STATE TO KGO;

CREATE VIEW SCAN_ORDERS_ALL_VIEW(
    ID,
    ORDER_DATE,
    ORDER_NUMBER,
    YEAR_NUMBER,
    ADDRESS,
    WORK_TYPE,
    LICENSED_ORGS_ID,
    OFFICES_ID,
    GIVEDOUT,
    RETURNED)
AS
SELECT
  SO.ID, SO.ORDER_DATE, SO.ORDER_NUMBER, SO.YEAR_NUMBER, SO.ADDRESS, SO.WORK_TYPE, SO.LICENSED_ORGS_ID, SO.OFFICES_ID,
  CASE WHEN EXISTS(SELECT SOMS.ID FROM SCAN_ORDER_MAP_STATE SOMS WHERE SOMS.GIVEDOUT = 1 AND SOMS.SCAN_ORDERS_ID = SO.ID) THEN 1 ELSE 0 END AS GIVEDOUT,
  CASE WHEN EXISTS(SELECT SOMS.ID FROM SCAN_ORDER_MAP_STATE SOMS WHERE SOMS.RETURNED = 0 AND SOMS.SCAN_ORDERS_ID = SO.ID) THEN 0 ELSE 1 END AS RETURNED
FROM SCAN_ORDERS SO
WHERE SO.ID > 0;

SET TERM ^ ;

CREATE OR ALTER PROCEDURE SAVE_SCAN_ORDER (
    ID INTEGER,
    ORDER_DATE DATE,
    ORDER_NUMBER VARCHAR(12),
    ADDRESS VARCHAR(1000),
    WORK_TYPE VARCHAR(1000),
    OFFICES_ID INTEGER,
    LICENSED_ORGS_ID INTEGER
)
AS
BEGIN
  IF (EXISTS(SELECT ID FROM SCAN_ORDERS WHERE (ID = :ID))) THEN
    UPDATE SCAN_ORDERS
    SET ORDER_DATE = :ORDER_DATE,
        ORDER_NUMBER = :ORDER_NUMBER,
        ADDRESS = :ADDRESS,
        WORK_TYPE = :WORK_TYPE,
        OFFICES_ID = :OFFICES_ID,
        LICENSED_ORGS_ID = :LICENSED_ORGS_ID
    WHERE (ID = :ID);
  ELSE
    INSERT INTO SCAN_ORDERS (
        ID, ORDER_DATE, ORDER_NUMBER, ADDRESS, WORK_TYPE,
        OFFICES_ID, LICENSED_ORGS_ID)
    VALUES (
        :ID, :ORDER_DATE, :ORDER_NUMBER, :ADDRESS, :WORK_TYPE,
        :OFFICES_ID, :LICENSED_ORGS_ID);
END^

SET TERM ; ^

GRANT SELECT,INSERT,UPDATE ON SCAN_ORDERS TO PROCEDURE SAVE_SCAN_ORDER;
GRANT SELECT ON SCAN_ORDER_MAPS TO VIEW SCAN_ORDER_MAP_STATE;
GRANT SELECT ON MAP_SCANS TO VIEW SCAN_ORDER_MAP_STATE;
GRANT SELECT ON MAP_SCANS_GIVEOUTS TO VIEW SCAN_ORDER_MAP_STATE;
GRANT SELECT ON SCAN_ORDERS TO VIEW SCAN_ORDERS_ALL_VIEW;
GRANT SELECT ON SCAN_ORDER_MAP_STATE TO VIEW SCAN_ORDERS_ALL_VIEW;
GRANT SELECT ON SCAN_ORDERS_ALL_VIEW TO KGO;
GRANT SELECT ON SCAN_ORDERS_ALL_VIEW TO SYSDBA;
GRANT SELECT ON SCAN_ORDERS_ALL_VIEW TO ADMINISTRATOR;
GRANT SELECT ON SCAN_ORDERS_ALL_VIEW TO KGO;
GRANT SELECT ON SCAN_ORDERS_ALL_VIEW TO SYSDBA;
GRANT SELECT ON SCAN_ORDERS_ALL_VIEW TO ADMINISTRATOR;
GRANT SELECT,DELETE ON SCAN_ORDERS TO KGO;
GRANT SELECT,DELETE ON SCAN_ORDERS TO SYSDBA;
GRANT SELECT,DELETE ON SCAN_ORDERS TO ADMINISTRATOR;
GRANT SELECT,INSERT,UPDATE,DELETE ON SCAN_ORDER_MAPS TO KGO;
GRANT SELECT,INSERT,UPDATE,DELETE ON SCAN_ORDER_MAPS TO SYSDBA;
GRANT SELECT,INSERT,UPDATE,DELETE ON SCAN_ORDER_MAPS TO ADMINISTRATOR;

GRANT EXECUTE ON PROCEDURE SAVE_SCAN_ORDER TO KGO;
GRANT EXECUTE ON PROCEDURE SAVE_SCAN_ORDER TO SYSDBA;
GRANT EXECUTE ON PROCEDURE SAVE_SCAN_ORDER TO ADMINISTRATOR;
