UPDATE SCAN_ORDERS
ALTER TABLE SCAN_ORDERS
ADD ANNULLED IBBOOL;

UPDATE SCAN_ORDERS
SET ANNULLED = 0;

DROP VIEW SCAN_ORDERS_ALL_VIEW;

CREATE VIEW SCAN_ORDERS_ALL_VIEW(
    ID,
    ORDER_DATE,
    ORDER_NUMBER,
    YEAR_NUMBER,
    ADDRESS,
    WORK_TYPE,
    LICENSED_ORGS_ID,
    OFFICES_ID,
    GIVEDOUT,
    RETURNED,
    ANNULLED)
AS
SELECT
  SO.ID, SO.ORDER_DATE, SO.ORDER_NUMBER, SO.YEAR_NUMBER, SO.ADDRESS, SO.WORK_TYPE, SO.LICENSED_ORGS_ID, SO.OFFICES_ID,
  CASE WHEN EXISTS(SELECT SOMS.ID FROM SCAN_ORDER_MAP_STATE SOMS WHERE SOMS.GIVEDOUT = 1 AND SOMS.SCAN_ORDERS_ID = SO.ID) THEN 1 ELSE 0 END AS GIVEDOUT,
  CASE WHEN EXISTS(SELECT SOMS.ID FROM SCAN_ORDER_MAP_STATE SOMS WHERE SOMS.RETURNED = 0 AND SOMS.SCAN_ORDERS_ID = SO.ID) THEN 0 ELSE 1 END AS RETURNED,
  SO.ANNULLED
FROM SCAN_ORDERS SO
WHERE SO.ID > 0
;

GRANT SELECT ON SCAN_ORDERS TO VIEW SCAN_ORDERS_ALL_VIEW;

GRANT SELECT ON SCAN_ORDER_MAP_STATE TO VIEW SCAN_ORDERS_ALL_VIEW;

GRANT SELECT ON SCAN_ORDERS_ALL_VIEW TO ADMINISTRATOR;

GRANT SELECT ON SCAN_ORDERS_ALL_VIEW TO KGO;


SET TERM ^ ;

CREATE OR ALTER PROCEDURE SAVE_SCAN_ORDER (
    ID INTEGER,
    ORDER_DATE DATE,
    ORDER_NUMBER VARCHAR(12),
    ADDRESS VARCHAR(1000),
    WORK_TYPE VARCHAR(1000),
    OFFICES_ID INTEGER,
    LICENSED_ORGS_ID INTEGER,
    ANNULLED SMALLINT)
AS
BEGIN
  IF (EXISTS(SELECT ID FROM SCAN_ORDERS WHERE (ID = :ID))) THEN
    UPDATE SCAN_ORDERS
    SET ORDER_DATE = :ORDER_DATE,
        ORDER_NUMBER = :ORDER_NUMBER,
        ADDRESS = :ADDRESS,
        WORK_TYPE = :WORK_TYPE,
        OFFICES_ID = :OFFICES_ID,
        LICENSED_ORGS_ID = :LICENSED_ORGS_ID,
        ANNULLED = :ANNULLED
    WHERE (ID = :ID);
  ELSE
    INSERT INTO SCAN_ORDERS (
        ID, ORDER_DATE, ORDER_NUMBER, ADDRESS, WORK_TYPE,
        OFFICES_ID, LICENSED_ORGS_ID, ANNULLED)
    VALUES (
        :ID, :ORDER_DATE, :ORDER_NUMBER, :ADDRESS, :WORK_TYPE,
        :OFFICES_ID, :LICENSED_ORGS_ID, :ANNULLED);
END^

SET TERM ; ^

ALTER TABLE MAP_SCANS_GIVEOUTS
ADD PERSON_WHO_TAKED_BACK_ID INTEGER;

ALTER TABLE MAP_SCANS_GIVEOUTS
ADD FILE_OPERATION_ID STRING50;

SET TERM ^ ;

CREATE OR ALTER PROCEDURE SAVE_MAP_SCAN_GIVEOUT (
    ID INTEGER,
    MAP_SCANS_ID INTEGER,
    DATE_OF_BACK DATE,
    DATE_OF_GIVE DATE,
    DEFINITION_NUMBER VARCHAR(10),
    GIVEN_OBJECT SMALLINT,
    HOLDER SMALLINT,
    HOLDER_NAME VARCHAR(300),
    ORDER_NUMBER VARCHAR(10),
    ORDERS_ID INTEGER,
    LICENSED_ORGS_ID INTEGER,
    PEOPLE_ID INTEGER,
    PERSON_WHO_GIVE_ID INTEGER,
    TERM_OF_GIVE INTEGER,
    ADDRESS VARCHAR(400),
    OFFICES_ID INTEGER,
    MD5_OLD VARCHAR(50),
    MD5_NEW VARCHAR(50),
    PERSON_WHO_TAKED_BACK_ID INTEGER,
    FILE_OPERATION_ID VARCHAR(50))
AS
BEGIN
  IF (EXISTS(SELECT ID FROM MAP_SCANS_GIVEOUTS WHERE (ID = :ID))) THEN
    UPDATE MAP_SCANS_GIVEOUTS
    SET MAP_SCANS_ID = :MAP_SCANS_ID,
        DATE_OF_BACK = :DATE_OF_BACK,
        DATE_OF_GIVE = :DATE_OF_GIVE,
        DEFINITION_NUMBER = :DEFINITION_NUMBER,
        GIVEN_OBJECT = :GIVEN_OBJECT,
        HOLDER = :HOLDER,
        HOLDER_NAME = :HOLDER_NAME,
        ORDER_NUMBER = :ORDER_NUMBER,
        ORDERS_ID = :ORDERS_ID,
        LICENSED_ORGS_ID = :LICENSED_ORGS_ID,
        PEOPLE_ID = :PEOPLE_ID,
        PERSON_WHO_GIVE_ID = :PERSON_WHO_GIVE_ID,
        TERM_OF_GIVE = :TERM_OF_GIVE,
        ADDRESS = :ADDRESS,
        OFFICES_ID = :OFFICES_ID,
        MD5_OLD = :MD5_OLD,
        MD5_NEW = :MD5_NEW,
        PERSON_WHO_TAKED_BACK_ID = :PERSON_WHO_TAKED_BACK_ID,
        FILE_OPERATION_ID = :FILE_OPERATION_ID
    WHERE (ID = :ID);
  ELSE
    INSERT INTO MAP_SCANS_GIVEOUTS (
        ID,
        MAP_SCANS_ID,
        DATE_OF_BACK,
        DATE_OF_GIVE,
        DEFINITION_NUMBER,
        GIVEN_OBJECT,
        HOLDER,
        HOLDER_NAME,
        ORDER_NUMBER,
        ORDERS_ID,
        LICENSED_ORGS_ID,
        PEOPLE_ID,
        PERSON_WHO_GIVE_ID,
        TERM_OF_GIVE,
        ADDRESS,
        OFFICES_ID,
        MD5_OLD,
        MD5_NEW,
        PERSON_WHO_TAKED_BACK_ID,
        FILE_OPERATION_ID
        )
    VALUES (
        :ID,
        :MAP_SCANS_ID,
        :DATE_OF_BACK,
        :DATE_OF_GIVE,
        :DEFINITION_NUMBER,
        :GIVEN_OBJECT,
        :HOLDER,
        :HOLDER_NAME,
        :ORDER_NUMBER,
        :ORDERS_ID,
        :LICENSED_ORGS_ID,
        :PEOPLE_ID,
        :PERSON_WHO_GIVE_ID,
        :TERM_OF_GIVE,
        :ADDRESS,
        :OFFICES_ID,
        :MD5_OLD,
        :MD5_NEW,
        :PERSON_WHO_TAKED_BACK_ID,
        :FILE_OPERATION_ID
        );
END^

SET TERM ; ^


