/* Server version: WI-V6.3.6.5026 Firebird 1.5 
   SQLDialect: 3. ODS: 10.1. Forced writes: On. Sweep interval: 20000.
   Page size: 1024. Cache pages: 75 (75 Kb). Read-only: False. */
SET NAMES WIN1251;

SET SQL DIALECT 3;

CONNECT 'localhost:C:\Projects\Db\UGA.fdb' USER 'SYSDBA' PASSWORD 'masterkey';

SET AUTODDL ON;

/* Drop Index... */
RECONNECT;

/* Drop: IDX_GIVEN_MAP_LIST_MAPS_ID (TIdxData) */
DROP INDEX IDX_GIVEN_MAP_LIST_MAPS_ID;


ALTER TABLE MAP_SCANS ADD HISTORY_FILE STRING255;

ALTER TABLE MAP_SCANS_GIVEOUTS ADD PERSON_WHO_TAKED_BACK_ID INTEGER;

ALTER TABLE MAP_SCANS_GIVEOUTS ADD FILE_OPERATION_ID STRING50;

ALTER TABLE SCAN_ORDERS ADD ANNULLED IBBOOL;

DESCRIBE FIELD STATUS TABLE MAP_SCANS_GIVEOUTS
'1 - файл выдан заказчику
2 - файл возвращён в базу';

/* Alter Field (Computed)... */
/* Drop MAP_SCANS(ACTUAL_MD5) for drop MAP_SCANS_GIVEOUTS(ACTUAL_MD5) */
ALTER TABLE MAP_SCANS DROP ACTUAL_MD5;

DROP VIEW SCAN_ORDERS_ALL_VIEW;

DROP VIEW SCAN_ORDER_MAP_STATE;

ALTER TABLE MAP_SCANS_GIVEOUTS DROP ACTUAL_MD5;

ALTER TABLE MAP_SCANS_GIVEOUTS ADD ACTUAL_MD5 COMPUTED BY ((CASE WHEN ((MD5_NEW IS NULL) OR (MD5_NEW = '')) THEN MD5_OLD ELSE MD5_NEW END));

DESCRIBE FIELD CAN_CREATE_ORDERS TABLE PEOPLE
'Человек может создавать и редактировать заказы.';


/* Drop table-fields... */
/* Empty SAVE_MAP_500 for drop MAP_500(SCAN_STATUS) */
SET TERM ^ ;

ALTER PROCEDURE SAVE_MAP_500(ID INTEGER,
NOMENCLATURE VARCHAR(20),
ORIGIN_YEAR INTEGER,
MAP_ORIGIN_ORG VARCHAR(300),
BASIS_TYPE VARCHAR(50),
STATUS SMALLINT,
ANNUL_DATE DATE,
SCAN_STATUS SMALLINT,
NUMBER VARCHAR(10),
IS_SECRET SMALLINT)
 AS
 BEGIN EXIT; END
^

SET TERM ; ^

ALTER TABLE MAP_500 DROP SCAN_STATUS;

ALTER TABLE MAP_500 DROP DATE_OF_SCAN;

/* Drop MAP_500(EXPIRED) for drop MAP_500(LAST_GIVE_ID) */
ALTER TABLE MAP_500 DROP EXPIRED;

/* Drop MAP_500(GIVE_STATUS) for drop MAP_500(LAST_GIVE_ID) */
/* Drop MAP_500(HOLDER_NAME) for drop MAP_500(GIVE_STATUS) */
ALTER TABLE MAP_500 DROP HOLDER_NAME;

/* Drop MAP_500(DATE_OF_GIVE) for drop MAP_500(GIVE_STATUS) */
ALTER TABLE MAP_500 DROP DATE_OF_GIVE;

ALTER TABLE MAP_500 DROP GIVE_STATUS;

/* Drop MAP_500(HOLDER_NAME) for drop MAP_500(LAST_GIVE_ID) */
/* Drop MAP_500(DATE_OF_GIVE) for drop MAP_500(LAST_GIVE_ID) */
ALTER TABLE MAP_500 DROP LAST_GIVE_ID;


/* Create view: SCAN_ORDER_MAP_STATE */
CREATE VIEW SCAN_ORDER_MAP_STATE(
ID,
SCAN_ORDERS_ID,
NOMENCLATURE,
GIVEOUT_ID,
GIVEDOUT,
RETURNED,
EXPIRED)
 AS 
SELECT SOM.ID, SOM.SCAN_ORDERS_ID, SOM.NOMENCLATURE, MSG.ID AS GIVEOUT_ID,
 CASE WHEN MSG.ID IS NULL THEN 0 ELSE 1 END AS GIVEDOUT,
 CASE WHEN MSG.DATE_OF_BACK IS NULL THEN 0 ELSE 1 END AS RETURNED,
 MSG.EXPIRED
FROM SCAN_ORDER_MAPS SOM
     LEFT JOIN MAP_SCANS_GIVEOUTS MSG ON (SOM.ID=MSG.SCAN_ORDER_MAPS_ID)
;

/* Create Views... */
/* Create view: MAP_500_GIVEOUTS_VIEW */
CREATE VIEW MAP_500_GIVEOUTS_VIEW(
ID,
GIVEOUT_ID)
 AS 
SELECT M.ID, MAX(GML.ID)
FROM MAP_500 M LEFT JOIN GIVEN_MAP_LIST GML ON (GML.MAP_500_ID=M.ID)
GROUP BY M.ID, GML.MAP_500_ID
;

ALTER TABLE MAP_SCANS ADD ACTUAL_MD5 COMPUTED BY ((SELECT MSG.ACTUAL_MD5 FROM MAP_SCANS_GIVEOUTS MSG WHERE MSG.ID = MAP_SCANS.LAST_GIVE_ID));

/* Create view: MAP_500_VIEW */
CREATE VIEW MAP_500_VIEW(
ID,
LAST_GIVE_ID,
EXPIRED,
GIVE_STATUS,
HOLDER_NAME,
DATE_OF_GIVE,
NOMENCLATURE,
ORIGIN_YEAR,
MAP_ORIGIN_ORG,
BASIS_TYPE,
STATUS,
ANNUL_DATE,
NUMBER,
IS_SECRET,
SCAN_STATUS,
DEFINITION_NUMBER,
DATE_OF_BACK,
GIVEN_OBJECT,
HOLDER,
ORDER_NUMBER,
ORDERS_ID,
LICENSED_ORGS_ID,
PEOPLE_ID,
PERSON_WHO_GIVE_ID,
TERM_OF_GIVE,
ADDRESS,
OFFICES_ID,
PEOPLE_NAME)
 AS 
SELECT
  MV.ID, MV.GIVEOUT_ID AS LAST_GIVE_ID, GML.EXPIRED, GML.STATUS AS GIVE_STATUS,
  (CASE GML.STATUS WHEN 1 THEN GML.HOLDER_NAME WHEN 0 THEN '' END) AS HOLDER_NAME,
  (CASE GML.STATUS WHEN 1 THEN GML.DATE_OF_GIVE WHEN 0 THEN NULL END) AS DATE_OF_GIVE,
  M.NOMENCLATURE, M.ORIGIN_YEAR, M.MAP_ORIGIN_ORG, M.BASIS_TYPE, M.STATUS,
  M.ANNUL_DATE, M.NUMBER, M.IS_SECRET,
  (CASE WHEN MS.NOMENCLATURE IS NULL THEN 0 ELSE 1 END) AS SCAN_STATUS,
  GML.DEFINITION_NUMBER,
  GML.DATE_OF_BACK, GML.GIVEN_OBJECT, GML.HOLDER, GML.ORDER_NUMBER,
  GML.ORDERS_ID, GML.LICENSED_ORGS_ID, GML.PEOPLE_ID, GML.PERSON_WHO_GIVE_ID,
  GML.TERM_OF_GIVE, GML.ADDRESS, GML.OFFICES_ID, GML.PEOPLE_NAME
  FROM MAP_500_GIVEOUTS_VIEW MV
  LEFT JOIN MAP_500 M ON (MV.ID = M.ID)
  LEFT JOIN GIVEN_MAP_LIST GML ON (MV.GIVEOUT_ID = GML.ID)
  LEFT JOIN MAP_SCANS MS ON (M.NOMENCLATURE = MS.NOMENCLATURE)
;

/* Create view: SCAN_ORDERS_ALL_VIEW */
CREATE VIEW SCAN_ORDERS_ALL_VIEW(
ID,
ORDER_DATE,
ORDER_NUMBER,
YEAR_NUMBER,
ADDRESS,
WORK_TYPE,
LICENSED_ORGS_ID,
OFFICES_ID,
GIVEDOUT,
RETURNED,
EXPIRED,
ANNULLED
)
 AS 
SELECT
  SO.ID, SO.ORDER_DATE, SO.ORDER_NUMBER, SO.YEAR_NUMBER, SO.ADDRESS, SO.WORK_TYPE, SO.LICENSED_ORGS_ID, SO.OFFICES_ID,
  CASE WHEN EXISTS(SELECT SOMS.ID FROM SCAN_ORDER_MAP_STATE SOMS WHERE SOMS.GIVEDOUT = 1 AND SOMS.SCAN_ORDERS_ID = SO.ID) THEN 1 ELSE 0 END AS GIVEDOUT,
  CASE WHEN EXISTS(SELECT SOMS.ID FROM SCAN_ORDER_MAP_STATE SOMS WHERE SOMS.RETURNED = 0 AND SOMS.SCAN_ORDERS_ID = SO.ID) THEN 0 ELSE 1 END AS RETURNED,
  CASE WHEN EXISTS(SELECT SOMS.ID FROM SCAN_ORDER_MAP_STATE SOMS WHERE SOMS.EXPIRED = 1 AND SOMS.SCAN_ORDERS_ID = SO.ID) THEN 1 ELSE 0 END AS EXPIRED,
  SO.ANNULLED
FROM SCAN_ORDERS SO
WHERE SO.ID > 0
;


/* Create index... */
CREATE DESC INDEX GIVEN_MAP_LIST_IDX1 ON GIVEN_MAP_LIST(DATE_OF_GIVE);

CREATE DESC INDEX GIVEN_MAP_LIST_IDX2 ON GIVEN_MAP_LIST(ID);

CREATE DESC INDEX GIVEN_MAP_LIST_IDX3 ON GIVEN_MAP_LIST(MAP_500_ID);


/* Alter index (Drop, Create)... */
RECONNECT;

/* Drop: MAP_SCANS_IDX1 (TIdxData) */
DROP INDEX MAP_SCANS_IDX1;

CREATE UNIQUE INDEX MAP_SCANS_IDX1 ON MAP_SCANS(NOMENCLATURE);


/* Create Unique... */
ALTER TABLE GIVEN_MAP_LIST ADD CONSTRAINT UNQ1_GIVEN_MAP_LIST UNIQUE (MAP_500_ID, ID);

/* Create Foreign Key... */
RECONNECT;

ALTER TABLE GIVEN_MAP_LIST ADD CONSTRAINT FK_GIVEN_MAP_LIST_1 FOREIGN KEY (MAP_500_ID) REFERENCES MAP_500 (ID) ON UPDATE CASCADE ON DELETE CASCADE;

DELETE FROM MAP_SCANS_GIVEOUTS;
COMMIT;
ALTER TABLE MAP_SCANS_GIVEOUTS ADD CONSTRAINT FK_MAP_SCANS_GIVEOUTS_1 FOREIGN KEY (MAP_SCANS_ID) REFERENCES MAP_SCANS (ID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE MAP_SCANS_GIVEOUTS ADD CONSTRAINT FK_MAP_SCANS_GIVEOUTS_2 FOREIGN KEY (SCAN_ORDER_MAPS_ID) REFERENCES SCAN_ORDER_MAPS (ID);

ALTER TABLE SCAN_ORDER_MAPS ADD CONSTRAINT FK_SCAN_ORDER_MAPS_1 FOREIGN KEY (SCAN_ORDERS_ID) REFERENCES SCAN_ORDERS (ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE SCAN_ORDERS ADD CONSTRAINT FK_SCAN_ORDERS_1 FOREIGN KEY (OFFICES_ID) REFERENCES OFFICES (ID);

ALTER TABLE SCAN_ORDERS ADD CONSTRAINT FK_SCAN_ORDERS_2 FOREIGN KEY (LICENSED_ORGS_ID) REFERENCES LICENSED_ORGS (ID);

/* Alter Procedure... */
/* Alter (SAVE_MAP_500) */
SET TERM ^ ;

ALTER PROCEDURE SAVE_MAP_500(ID INTEGER,
NOMENCLATURE VARCHAR(20),
ORIGIN_YEAR INTEGER,
MAP_ORIGIN_ORG VARCHAR(300),
BASIS_TYPE VARCHAR(50),
STATUS SMALLINT,
ANNUL_DATE DATE,
NUMBER VARCHAR(10),
IS_SECRET SMALLINT)
 AS
BEGIN
  IF (EXISTS(SELECT ID FROM MAP_500 WHERE (ID = :ID))) THEN
    UPDATE MAP_500
    SET NOMENCLATURE = :NOMENCLATURE,
        ORIGIN_YEAR = :ORIGIN_YEAR,
        MAP_ORIGIN_ORG = :MAP_ORIGIN_ORG,
        BASIS_TYPE = :BASIS_TYPE,
        STATUS = :STATUS,
        ANNUL_DATE = :ANNUL_DATE,
        NUMBER = :NUMBER,
        IS_SECRET = :IS_SECRET
    WHERE (ID = :ID);
  ELSE
    INSERT INTO MAP_500 (
        ID,
        NOMENCLATURE,
        ORIGIN_YEAR,
        MAP_ORIGIN_ORG,
        BASIS_TYPE,
        STATUS,
        ANNUL_DATE,
        NUMBER,
        IS_SECRET)
    VALUES (
        :ID,
        :NOMENCLATURE,
        :ORIGIN_YEAR,
        :MAP_ORIGIN_ORG,
        :BASIS_TYPE,
        :STATUS,
        :ANNUL_DATE,
        :NUMBER,
        :IS_SECRET);
END
^

/* Alter (SAVE_MAP_SCAN) */
ALTER PROCEDURE SAVE_MAP_SCAN(ID INTEGER,
NOMENCLATURE VARCHAR(20),
START_DATE DATE,
IS_SECRET SMALLINT,
HISTORY_FILE VARCHAR(255))
 AS
BEGIN
  IF (EXISTS(SELECT ID FROM MAP_SCANS WHERE (ID = :ID))) THEN
    UPDATE MAP_SCANS
    SET NOMENCLATURE = :NOMENCLATURE,
        START_DATE = :START_DATE,
        IS_SECRET = :IS_SECRET,
        HISTORY_FILE = :HISTORY_FILE
    WHERE (ID = :ID);
  ELSE
    INSERT INTO MAP_SCANS (
        ID,
        NOMENCLATURE,
        START_DATE,
        IS_SECRET,
        HISTORY_FILE)
    VALUES (
        :ID,
        :NOMENCLATURE,
        :START_DATE,
        :IS_SECRET,
        :HISTORY_FILE);
END
^

/* Alter (SAVE_MAP_SCAN_GIVEOUT) */
ALTER PROCEDURE SAVE_MAP_SCAN_GIVEOUT(ID INTEGER,
MAP_SCANS_ID INTEGER,
DATE_OF_BACK DATE,
DATE_OF_GIVE DATE,
DEFINITION_NUMBER VARCHAR(10),
GIVEN_OBJECT SMALLINT,
HOLDER SMALLINT,
HOLDER_NAME VARCHAR(300),
ORDER_NUMBER VARCHAR(10),
ORDERS_ID INTEGER,
LICENSED_ORGS_ID INTEGER,
PEOPLE_ID INTEGER,
PERSON_WHO_GIVE_ID INTEGER,
TERM_OF_GIVE INTEGER,
ADDRESS VARCHAR(400),
OFFICES_ID INTEGER,
MD5_OLD VARCHAR(50),
MD5_NEW VARCHAR(50),
PERSON_WHO_TAKED_BACK_ID INTEGER,
FILE_OPERATION_ID VARCHAR(50),
PEOPLE_NAME VARCHAR(100))
 AS
BEGIN
  IF (EXISTS(SELECT ID FROM MAP_SCANS_GIVEOUTS WHERE (ID = :ID))) THEN
    UPDATE MAP_SCANS_GIVEOUTS
    SET MAP_SCANS_ID = :MAP_SCANS_ID,
        DATE_OF_BACK = :DATE_OF_BACK,
        DATE_OF_GIVE = :DATE_OF_GIVE,
        DEFINITION_NUMBER = :DEFINITION_NUMBER,
        GIVEN_OBJECT = :GIVEN_OBJECT,
        HOLDER = :HOLDER,
        HOLDER_NAME = :HOLDER_NAME,
        ORDER_NUMBER = :ORDER_NUMBER,
        ORDERS_ID = :ORDERS_ID,
        LICENSED_ORGS_ID = :LICENSED_ORGS_ID,
        PEOPLE_ID = :PEOPLE_ID,
        PERSON_WHO_GIVE_ID = :PERSON_WHO_GIVE_ID,
        TERM_OF_GIVE = :TERM_OF_GIVE,
        ADDRESS = :ADDRESS,
        OFFICES_ID = :OFFICES_ID,
        MD5_OLD = :MD5_OLD,
        MD5_NEW = :MD5_NEW,
        PERSON_WHO_TAKED_BACK_ID = :PERSON_WHO_TAKED_BACK_ID,
        FILE_OPERATION_ID = :FILE_OPERATION_ID,
        PEOPLE_NAME = :PEOPLE_NAME
    WHERE (ID = :ID);
  ELSE
    INSERT INTO MAP_SCANS_GIVEOUTS (
        ID,
        MAP_SCANS_ID,
        DATE_OF_BACK,
        DATE_OF_GIVE,
        DEFINITION_NUMBER,
        GIVEN_OBJECT,
        HOLDER,
        HOLDER_NAME,
        ORDER_NUMBER,
        ORDERS_ID,
        LICENSED_ORGS_ID,
        PEOPLE_ID,
        PERSON_WHO_GIVE_ID,
        TERM_OF_GIVE,
        ADDRESS,
        OFFICES_ID,
        MD5_OLD,
        MD5_NEW,
        PERSON_WHO_TAKED_BACK_ID,
        FILE_OPERATION_ID,
        PEOPLE_NAME
        )
    VALUES (
        :ID,
        :MAP_SCANS_ID,
        :DATE_OF_BACK,
        :DATE_OF_GIVE,
        :DEFINITION_NUMBER,
        :GIVEN_OBJECT,
        :HOLDER,
        :HOLDER_NAME,
        :ORDER_NUMBER,
        :ORDERS_ID,
        :LICENSED_ORGS_ID,
        :PEOPLE_ID,
        :PERSON_WHO_GIVE_ID,
        :TERM_OF_GIVE,
        :ADDRESS,
        :OFFICES_ID,
        :MD5_OLD,
        :MD5_NEW,
        :PERSON_WHO_TAKED_BACK_ID,
        :FILE_OPERATION_ID,
        :PEOPLE_NAME
        );
END
^

/* Alter (SAVE_SCAN_ORDER) */
ALTER PROCEDURE SAVE_SCAN_ORDER(ID INTEGER,
ORDER_DATE DATE,
ORDER_NUMBER VARCHAR(12),
ADDRESS VARCHAR(1000),
WORK_TYPE VARCHAR(1000),
OFFICES_ID INTEGER,
LICENSED_ORGS_ID INTEGER,
ANNULLED SMALLINT)
 AS
BEGIN
  IF (EXISTS(SELECT ID FROM SCAN_ORDERS WHERE (ID = :ID))) THEN
    UPDATE SCAN_ORDERS
    SET ORDER_DATE = :ORDER_DATE,
        ORDER_NUMBER = :ORDER_NUMBER,
        ADDRESS = :ADDRESS,
        WORK_TYPE = :WORK_TYPE,
        OFFICES_ID = :OFFICES_ID,
        LICENSED_ORGS_ID = :LICENSED_ORGS_ID,
        ANNULLED = :ANNULLED
    WHERE (ID = :ID);
  ELSE
    INSERT INTO SCAN_ORDERS (
        ID, ORDER_DATE, ORDER_NUMBER, ADDRESS, WORK_TYPE,
        OFFICES_ID, LICENSED_ORGS_ID, ANNULLED)
    VALUES (
        :ID, :ORDER_DATE, :ORDER_NUMBER, :ADDRESS, :WORK_TYPE,
        :OFFICES_ID, :LICENSED_ORGS_ID, :ANNULLED);
END
^

/* Create Views... */

SET TERM ; ^




