CREATE GENERATOR MAP_SCANS_GIVEOUTS;
CREATE GENERATOR MAP_SCANS_HISTORY;
CREATE GENERATOR MAP_SCANS_FIGURE;

CREATE TABLE MAP_SCAN_HISTORY (
    ID                       INTEGER NOT NULL,
    MAP_SCANS_ID             INTEGER NOT NULL,
    CHIEF                    STRING100 COLLATE PXW_CYRL /* STRING100 = VARCHAR(100) */,
    CURRENT_CHANGES_MAPPING  STRING20 COLLATE PXW_CYRL /* STRING20 = VARCHAR(20) */,
    DATE_OF_ACCEPT           DATE,
    DATE_OF_WORKS            DATE,
    DRAFT_WORKS_EXECUTOR     STRING100 COLLATE PXW_CYRL /* STRING100 = VARCHAR(100) */,
    ENGIN_NET_MAPPING        STRING20 COLLATE PXW_CYRL /* STRING20 = VARCHAR(20) */,
    HIGH_RISE_MAPPING        STRING20 COLLATE PXW_CYRL /* STRING20 = VARCHAR(20) */,
    HORIZONTAL_MAPPING       STRING20 COLLATE PXW_CYRL /* STRING20 = VARCHAR(20) */,
    MENS_MAPPING             STRING20 COLLATE PXW_CYRL /* STRING20 = VARCHAR(20) */,
    NEWLY_BUILDING_MAPPING   STRING20 COLLATE PXW_CYRL /* STRING20 = VARCHAR(20) */,
    ORDER_NUMBER             NUMBER_CHAR COLLATE PXW_CYRL /* NUMBER_CHAR = VARCHAR(12) */,
    TACHEOMETRIC_MAPPING     STRING20 COLLATE PXW_CYRL /* STRING20 = VARCHAR(20) */,
    TOTAL_SUM                STRING20 COLLATE PXW_CYRL /* STRING20 = VARCHAR(20) */,
    WORKS_EXECUTOR           STRING100 COLLATE PXW_CYRL /* STRING100 = VARCHAR(100) */,
    EXECUTOR                 STRING100 COLLATE PXW_CYRL /* STRING100 = VARCHAR(100) */
);

ALTER TABLE MAP_SCAN_HISTORY ADD CONSTRAINT PK_MAP_SCAN_HISTORY PRIMARY KEY (ID);

ALTER TABLE MAP_SCAN_HISTORY
ADD CONSTRAINT FK_MAP_SCAN_HISTORY_SCAN_ID
FOREIGN KEY (MAP_SCANS_ID)
REFERENCES MAP_SCANS(ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

CREATE TABLE MAP_SCAN_FIGURES (
    ID                  INTEGER NOT NULL,
    HISTORY_ELEMENT_ID  INTEGER NOT NULL,
    FIGURE_TYPE         IBBOOL NOT NULL /* IBBOOL = SMALLINT DEFAULT 0 NOT NULL CHECK (VALUE IN (0, 1)) */,
    FIGURE_COLOR        INTEGER,
    EXTENT_LEFT         SMALLINT,
    EXTENT_RIGHT        SMALLINT,
    EXTENT_TOP          SMALLINT,
    EXTENT_BOTTOM       SMALLINT
);
ALTER TABLE MAP_SCAN_FIGURES
ADD CONSTRAINT PK_MAP_SCAN_FIGURES
PRIMARY KEY (ID);

ALTER TABLE MAP_SCAN_FIGURES
ADD CONSTRAINT FK_MAP_SCAN_FIGURES_HISTORY_ID
FOREIGN KEY (HISTORY_ELEMENT_ID)
REFERENCES MAP_SCAN_HISTORY(ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

CREATE TABLE MAP_SCAN_FIGURE_POINTS (
    ID         INTEGER NOT NULL,
    FIGURE_ID  INTEGER NOT NULL,
    X          SMALLINT NOT NULL,
    Y          SMALLINT NOT NULL
);
ALTER TABLE MAP_SCAN_FIGURE_POINTS
ADD CONSTRAINT PK_MAP_SCAN_FIGURE_POINTS
PRIMARY KEY (ID);

ALTER TABLE MAP_SCAN_FIGURE_POINTS
ADD CONSTRAINT FK_MAP_SCAN_FIGURE_POINTS_1
FOREIGN KEY (FIGURE_ID)
REFERENCES MAP_SCAN_FIGURES(ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

SET TERM ^ ;

CREATE OR ALTER PROCEDURE SAVE_MAP_SCAN_HISTORY (
    ID INTEGER,
    MAP_SCANS_ID INTEGER,
    CHIEF VARCHAR(100),
    CURRENT_CHANGES_MAPPING VARCHAR(20),
    DATE_OF_ACCEPT DATE,
    DATE_OF_WORKS DATE,
    DRAFT_WORKS_EXECUTOR VARCHAR(100),
    ENGIN_NET_MAPPING VARCHAR(20),
    HIGH_RISE_MAPPING VARCHAR(20),
    HORIZONTAL_MAPPING VARCHAR(20),
    MENS_MAPPING VARCHAR(20),
    NEWLY_BUILDING_MAPPING VARCHAR(20),
    ORDER_NUMBER VARCHAR(10),
    TACHEOMETRIC_MAPPING VARCHAR(20),
    TOTAL_SUM VARCHAR(20),
    EXECUTOR VARCHAR(100))
AS
BEGIN
  IF (EXISTS(SELECT ID FROM MAP_SCAN_HISTORY WHERE (ID = :ID))) THEN
    UPDATE MAP_SCAN_HISTORY
    SET MAP_SCANS_ID = :MAP_SCANS_ID,
        ORDER_NUMBER = :ORDER_NUMBER,
        DATE_OF_WORKS = :DATE_OF_WORKS,
        EXECUTOR = :EXECUTOR,
        HIGH_RISE_MAPPING = :HIGH_RISE_MAPPING,
        HORIZONTAL_MAPPING = :HORIZONTAL_MAPPING,
        MENS_MAPPING = :MENS_MAPPING,
        TACHEOMETRIC_MAPPING = :TACHEOMETRIC_MAPPING,
        CURRENT_CHANGES_MAPPING = :CURRENT_CHANGES_MAPPING,
        NEWLY_BUILDING_MAPPING = :NEWLY_BUILDING_MAPPING,
        ENGIN_NET_MAPPING = :ENGIN_NET_MAPPING,
        TOTAL_SUM = :TOTAL_SUM,
        DRAFT_WORKS_EXECUTOR = :DRAFT_WORKS_EXECUTOR,
        CHIEF = :CHIEF,
        DATE_OF_ACCEPT = :DATE_OF_ACCEPT
    WHERE (ID = :ID);
  ELSE
    INSERT INTO MAP_SCAN_HISTORY (
        ID,
        MAP_SCANS_ID,
        ORDER_NUMBER,
        DATE_OF_WORKS,
        EXECUTOR,
        HIGH_RISE_MAPPING,
        HORIZONTAL_MAPPING,
        MENS_MAPPING,
        TACHEOMETRIC_MAPPING,
        CURRENT_CHANGES_MAPPING,
        NEWLY_BUILDING_MAPPING,
        ENGIN_NET_MAPPING,
        TOTAL_SUM,
        DRAFT_WORKS_EXECUTOR,
        CHIEF,
        DATE_OF_ACCEPT)
    VALUES (
        :ID,
        :MAP_SCANS_ID,
        :ORDER_NUMBER,
        :DATE_OF_WORKS,
        :EXECUTOR,
        :HIGH_RISE_MAPPING,
        :HORIZONTAL_MAPPING,
        :MENS_MAPPING,
        :TACHEOMETRIC_MAPPING,
        :CURRENT_CHANGES_MAPPING,
        :NEWLY_BUILDING_MAPPING,
        :ENGIN_NET_MAPPING,
        :TOTAL_SUM,
        :DRAFT_WORKS_EXECUTOR,
        :CHIEF,
        :DATE_OF_ACCEPT);
END^

SET TERM ; ^

/* Following GRANT statetements are generated automatically */

GRANT SELECT,INSERT,UPDATE ON MAP_SCAN_HISTORY TO PROCEDURE SAVE_MAP_SCAN_HISTORY;






