ALTER TABLE MAP_SCAN_HISTORY
ADD CHIEF_1                      STRING300,
ADD CURRENT_CHANGES_MAPPING_1    STRING300,
ADD DRAFT_WORKS_EXECUTOR_1       STRING300,
ADD ENGIN_NET_MAPPING_1          STRING300,
ADD HIGH_RISE_MAPPING_1          STRING300,
ADD HORIZONTAL_MAPPING_1         STRING300,
ADD MENS_MAPPING_1               STRING300,
ADD NEWLY_BUILDING_MAPPING_1     STRING300,
ADD TACHEOMETRIC_MAPPING_1       STRING300,
ADD TOTAL_SUM_1                  STRING300,
ADD WORKS_EXECUTOR_1             STRING300,
ADD EXECUTOR_1                   STRING300;


SET TERM ^ ;

CREATE OR ALTER PROCEDURE SAVE_MAP_SCAN_HISTORY (
    ID INTEGER,
    MAP_SCANS_ID INTEGER,
    CHIEF VARCHAR(300),
    CURRENT_CHANGES_MAPPING VARCHAR(300),
    DATE_OF_ACCEPT DATE,
    DATE_OF_WORKS DATE,
    DRAFT_WORKS_EXECUTOR VARCHAR(300),
    ENGIN_NET_MAPPING VARCHAR(300),
    HIGH_RISE_MAPPING VARCHAR(300),
    HORIZONTAL_MAPPING VARCHAR(300),
    MENS_MAPPING VARCHAR(300),
    NEWLY_BUILDING_MAPPING VARCHAR(300),
    ORDER_NUMBER VARCHAR(10),
    TACHEOMETRIC_MAPPING VARCHAR(300),
    TOTAL_SUM VARCHAR(300),
    EXECUTOR VARCHAR(300))
AS
BEGIN

END^

SET TERM ; ^
;

UPDATE MAP_SCAN_HISTORY
SET
    CHIEF_1 = CHIEF,
    CURRENT_CHANGES_MAPPING_1 = CURRENT_CHANGES_MAPPING,
    DRAFT_WORKS_EXECUTOR_1 = DRAFT_WORKS_EXECUTOR,
    ENGIN_NET_MAPPING_1 = ENGIN_NET_MAPPING,
    HIGH_RISE_MAPPING_1 = HIGH_RISE_MAPPING,
    HORIZONTAL_MAPPING_1 = HORIZONTAL_MAPPING,
    MENS_MAPPING_1 = MENS_MAPPING,
    NEWLY_BUILDING_MAPPING_1 = NEWLY_BUILDING_MAPPING,
    TACHEOMETRIC_MAPPING_1 = TACHEOMETRIC_MAPPING,
    TOTAL_SUM_1 = TOTAL_SUM,
    WORKS_EXECUTOR_1 = WORKS_EXECUTOR,
    EXECUTOR_1 = EXECUTOR;

ALTER TABLE MAP_SCAN_HISTORY
DROP CHIEF,
DROP CURRENT_CHANGES_MAPPING, 
DROP DRAFT_WORKS_EXECUTOR,
DROP ENGIN_NET_MAPPING, 
DROP HIGH_RISE_MAPPING, 
DROP HORIZONTAL_MAPPING, 
DROP MENS_MAPPING, 
DROP NEWLY_BUILDING_MAPPING, 
DROP TACHEOMETRIC_MAPPING,
DROP TOTAL_SUM, 
DROP WORKS_EXECUTOR, 
DROP EXECUTOR;

ALTER TABLE MAP_SCAN_HISTORY
ALTER CHIEF_1 TO CHIEF,
ALTER CURRENT_CHANGES_MAPPING_1 TO CURRENT_CHANGES_MAPPING, 
ALTER DRAFT_WORKS_EXECUTOR_1 TO DRAFT_WORKS_EXECUTOR,
ALTER ENGIN_NET_MAPPING_1 TO ENGIN_NET_MAPPING, 
ALTER HIGH_RISE_MAPPING_1 TO HIGH_RISE_MAPPING, 
ALTER HORIZONTAL_MAPPING_1 TO HORIZONTAL_MAPPING, 
ALTER MENS_MAPPING_1 TO MENS_MAPPING, 
ALTER NEWLY_BUILDING_MAPPING_1 TO NEWLY_BUILDING_MAPPING, 
ALTER TACHEOMETRIC_MAPPING_1 TO TACHEOMETRIC_MAPPING,
ALTER TOTAL_SUM_1 TO TOTAL_SUM, 
ALTER WORKS_EXECUTOR_1 TO WORKS_EXECUTOR, 
ALTER EXECUTOR_1 TO EXECUTOR;


SET TERM ^ ;


CREATE OR ALTER PROCEDURE SAVE_MAP_SCAN_HISTORY (
    ID INTEGER,
    MAP_SCANS_ID INTEGER,
    CHIEF VARCHAR(300),
    CURRENT_CHANGES_MAPPING VARCHAR(300),
    DATE_OF_ACCEPT DATE,
    DATE_OF_WORKS DATE,
    DRAFT_WORKS_EXECUTOR VARCHAR(300),
    ENGIN_NET_MAPPING VARCHAR(300),
    HIGH_RISE_MAPPING VARCHAR(300),
    HORIZONTAL_MAPPING VARCHAR(300),
    MENS_MAPPING VARCHAR(300),
    NEWLY_BUILDING_MAPPING VARCHAR(300),
    ORDER_NUMBER VARCHAR(10),
    TACHEOMETRIC_MAPPING VARCHAR(300),
    TOTAL_SUM VARCHAR(300),
    EXECUTOR VARCHAR(300))
AS
BEGIN
  IF (EXISTS(SELECT ID FROM MAP_SCAN_HISTORY WHERE (ID = :ID))) THEN
    UPDATE MAP_SCAN_HISTORY
    SET MAP_SCANS_ID = :MAP_SCANS_ID,
        ORDER_NUMBER = :ORDER_NUMBER,
        DATE_OF_WORKS = :DATE_OF_WORKS,
        EXECUTOR = :EXECUTOR,
        HIGH_RISE_MAPPING = :HIGH_RISE_MAPPING,
        HORIZONTAL_MAPPING = :HORIZONTAL_MAPPING,
        MENS_MAPPING = :MENS_MAPPING,
        TACHEOMETRIC_MAPPING = :TACHEOMETRIC_MAPPING,
        CURRENT_CHANGES_MAPPING = :CURRENT_CHANGES_MAPPING,
        NEWLY_BUILDING_MAPPING = :NEWLY_BUILDING_MAPPING,
        ENGIN_NET_MAPPING = :ENGIN_NET_MAPPING,
        TOTAL_SUM = :TOTAL_SUM,
        DRAFT_WORKS_EXECUTOR = :DRAFT_WORKS_EXECUTOR,
        CHIEF = :CHIEF,
        DATE_OF_ACCEPT = :DATE_OF_ACCEPT
    WHERE (ID = :ID);
  ELSE
    INSERT INTO MAP_SCAN_HISTORY (
        ID,
        MAP_SCANS_ID,
        ORDER_NUMBER,
        DATE_OF_WORKS,
        EXECUTOR,
        HIGH_RISE_MAPPING,
        HORIZONTAL_MAPPING,
        MENS_MAPPING,
        TACHEOMETRIC_MAPPING,
        CURRENT_CHANGES_MAPPING,
        NEWLY_BUILDING_MAPPING,
        ENGIN_NET_MAPPING,
        TOTAL_SUM,
        DRAFT_WORKS_EXECUTOR,
        CHIEF,
        DATE_OF_ACCEPT)
    VALUES (
        :ID,
        :MAP_SCANS_ID,
        :ORDER_NUMBER,
        :DATE_OF_WORKS,
        :EXECUTOR,
        :HIGH_RISE_MAPPING,
        :HORIZONTAL_MAPPING,
        :MENS_MAPPING,
        :TACHEOMETRIC_MAPPING,
        :CURRENT_CHANGES_MAPPING,
        :NEWLY_BUILDING_MAPPING,
        :ENGIN_NET_MAPPING,
        :TOTAL_SUM,
        :DRAFT_WORKS_EXECUTOR,
        :CHIEF,
        :DATE_OF_ACCEPT);
END^

SET TERM ; ^

DROP VIEW SCAN_ORDERS_ALL_VIEW;

CREATE VIEW SCAN_ORDERS_ALL_VIEW(
    ID,
    ORDER_DATE,
    ORDER_NUMBER,
    YEAR_NUMBER,
    ADDRESS,
    WORK_TYPE,
    LICENSED_ORGS_ID,
    OFFICES_ID,
    GIVEDOUT,
    RETURNED,
    EXPIRED,
    ANNULLED)
AS
SELECT
  SO.ID, SO.ORDER_DATE, SO.ORDER_NUMBER, SO.YEAR_NUMBER, SO.ADDRESS, SO.WORK_TYPE, SO.LICENSED_ORGS_ID, SO.OFFICES_ID,
  CASE WHEN EXISTS(SELECT SOMS.ID FROM SCAN_ORDER_MAP_STATE SOMS WHERE SOMS.GIVEDOUT = 0 AND SOMS.SCAN_ORDERS_ID = SO.ID) THEN 0 ELSE 1 END AS GIVEDOUT,
  CASE WHEN EXISTS(SELECT SOMS.ID FROM SCAN_ORDER_MAP_STATE SOMS WHERE SOMS.RETURNED = 0 AND SOMS.SCAN_ORDERS_ID = SO.ID) THEN 0 ELSE 1 END AS RETURNED,
  CASE WHEN EXISTS(SELECT SOMS.ID FROM SCAN_ORDER_MAP_STATE SOMS WHERE SOMS.EXPIRED = 1 AND SOMS.SCAN_ORDERS_ID = SO.ID) THEN 1 ELSE 0 END AS EXPIRED,
  SO.ANNULLED
FROM SCAN_ORDERS SO
WHERE SO.ID > 0
;

GRANT SELECT ON SCAN_ORDERS TO VIEW SCAN_ORDERS_ALL_VIEW;

GRANT SELECT ON SCAN_ORDER_MAP_STATE TO VIEW SCAN_ORDERS_ALL_VIEW;

GRANT SELECT ON SCAN_ORDERS_ALL_VIEW TO ADMINISTRATOR;


