
CREATE TABLE WATERMARK_PARAMETERS (
    WATERMARK_TEXT  STRING1000 NOT NULL ,
    FONT_NAME       STRING100 NOT NULL ,
    FONT_SIZE       SMALLINT NOT NULL,
    BORDER_SIZE     SMALLINT NOT NULL,
    TEXT_WIDTH      INTEGER NOT NULL,
    TEXT_HEIGHT     INTEGER NOT NULL,
    BORDER_COLOR_A  SMALLINT NOT NULL,
    BORDER_COLOR_R  SMALLINT NOT NULL,
    BORDER_COLOR_G  SMALLINT NOT NULL,
    BORDER_COLOR_B  SMALLINT NOT NULL,
    INNER_COLOR_A   SMALLINT NOT NULL,
    INNER_COLOR_R   SMALLINT NOT NULL,
    INNER_COLOR_G   SMALLINT NOT NULL,
    INNER_COLOR_B   SMALLINT NOT NULL
);

ALTER TABLE PARAMETERS ADD COLUMN MAP_REPORT_ERROR_MODE SMALLINT;

CREATE GENERATOR ORDER_MAPS_GEN;
SET GENERATOR ORDER_MAPS_GEN TO 0;

CREATE TABLE ORDER_MAPS (
    ID            ID NOT NULL /* ID = INTEGER DEFAULT 0 NOT NULL */,
    ORDERS_ID     INTEGER,
    NOMENCLATURE  STRING20 /* STRING20 = VARCHAR(20) */
);

ALTER TABLE ORDER_MAPS ADD CONSTRAINT FK_ORDER_MAPS_ON_ORDERS_ID FOREIGN KEY (ORDERS_ID) REFERENCES ORDERS (ID) ON DELETE CASCADE ON UPDATE CASCADE;
CREATE UNIQUE INDEX ORDER_MAPS_IDX_ID_NOMENCLATURE ON ORDER_MAPS (ID, NOMENCLATURE);
/* Privileges of users */
GRANT ALL ON ORDER_MAPS TO PUBLIC;




