unit TestMstImportMidMif;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework,
  StrUtils, Classes, Contnrs, SysUtils, uGC, uMstImport, uMstImportMidMif;

type
  TestTLineSplitter = class(TTestCase)
  strict private
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestSplit;
  end;

implementation

procedure TestTLineSplitter.SetUp;
begin

end;

procedure TestTLineSplitter.TearDown;
begin
  
end;

procedure TestTLineSplitter.TestSplit;
var
  Splitter: TLineSplitter;
  Parts: TStringList;
begin
  Parts := TStringList.Create;
  Parts.Forget();
  Splitter.Separator := ' ';
//Version 300
  Splitter.Line := 'Version 300';
  Splitter.Split(Parts);
  CheckEquals(Parts.Count, 2);
  CheckEquals(Parts[0], 'Version');
  CheckEquals(Parts[1], '300');
//Charset "WindowsCyrillic"
  Splitter.Line := 'Charset "WindowsCyrillic"';
  Splitter.Split(Parts);
  CheckEquals(Parts.Count, 2);
  CheckEquals(Parts[0], 'Charset');
  CheckEquals(Parts[1], 'WindowsCyrillic');
//Delimiter ","
//CoordSys Earth Projection 8, 1001, "m", 21, 0, 1, 4500000, 0 Bounds (-3749281.53901, -10002137.4978) (12749281.539, 10002137.4978)
//Columns 13
//  Вид_пользования Char(64)
//  Графа_по_экспликации Float
//  Дом Char(64)
//  З_п_ Char(64)
//  Категория_по_экспликации Float
//  Нас_пункт Char(64)
//  Номер_дома Float
//  Под_застройкой Float
//  Слова Char(64)
//  Улица Char(64)
//  Физ_лицо SmallInt
//  Цифра_1 Integer
//  Разл_названия Char(64)
//Data
  Splitter.Line := 'Data';
  Splitter.Split(Parts);
  CheckEquals(Parts.Count, 1);
  CheckEquals(Parts[0], 'Data');
  //
  Splitter.Separator := '___';
  Splitter.Line := 'Data___Data';
  Splitter.Split(Parts);
  CheckEquals(Parts.Count, 2);
  CheckEquals(Parts[0], 'Data');
  CheckEquals(Parts[1], 'Data');
  Splitter.Line := 'Data___Data___';
  Splitter.Split(Parts);
  CheckEquals(Parts.Count, 2);
  CheckEquals(Parts[0], 'Data');
  CheckEquals(Parts[1], 'Data');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTLineSplitter.Suite);
end.
