CREATE TABLE MASTER_PLAN_LAYERS (
    ID ID NOT NULL,
    NAME STRING255 NOT NULL /* COLLATE WIN1251 - default */,
    IS_GROUP IBBOOL,
    GROUP_ID ID,
    LINE_COLOR STRING10 /* COLLATE WIN1251 - default */);
COMMIT WORK;
ALTER TABLE MASTER_PLAN_LAYERS ADD CONSTRAINT PK_MASTER_PLAN_LAYERS PRIMARY KEY (ID) ;
COMMIT WORK;
INSERT INTO MASTER_PLAN_LAYERS (ID, NAME, IS_GROUP, GROUP_ID, LINE_COLOR)
                        VALUES (1, 'газ', 0, 0, '$FFFF80');
INSERT INTO MASTER_PLAN_LAYERS (ID, NAME, IS_GROUP, GROUP_ID, LINE_COLOR)
                        VALUES (2, 'вода', 0, 0, '$228B22');
INSERT INTO MASTER_PLAN_LAYERS (ID, NAME, IS_GROUP, GROUP_ID, LINE_COLOR)
                        VALUES (3, 'канализация', 0, 0, '$0000FF');
INSERT INTO MASTER_PLAN_LAYERS (ID, NAME, IS_GROUP, GROUP_ID, LINE_COLOR)
                        VALUES (4, 'канализация ливневая', 0, 0, '$00FF00');
INSERT INTO MASTER_PLAN_LAYERS (ID, NAME, IS_GROUP, GROUP_ID, LINE_COLOR)
                        VALUES (5, 'кабели', 0, 1012, '$000000');
INSERT INTO MASTER_PLAN_LAYERS (ID, NAME, IS_GROUP, GROUP_ID, LINE_COLOR)
                        VALUES (6, 'ЛЭП', 0, 1012, '$000000');
INSERT INTO MASTER_PLAN_LAYERS (ID, NAME, IS_GROUP, GROUP_ID, LINE_COLOR)
                        VALUES (7, 'подзем/метал защита', 0, 1012, '$00FFFF');
INSERT INTO MASTER_PLAN_LAYERS (ID, NAME, IS_GROUP, GROUP_ID, LINE_COLOR)
                        VALUES (8, 'теплосети ', 0, 0, '$FF4500');
INSERT INTO MASTER_PLAN_LAYERS (ID, NAME, IS_GROUP, GROUP_ID, LINE_COLOR)
                        VALUES (9, 'прочее', 0, 0, '$000000');
INSERT INTO MASTER_PLAN_LAYERS (ID, NAME, IS_GROUP, GROUP_ID, LINE_COLOR)
                        VALUES (10, 'столбы', 0, 0, '$293E56');
INSERT INTO MASTER_PLAN_LAYERS (ID, NAME, IS_GROUP, GROUP_ID, LINE_COLOR)
                        VALUES (11, 'связь', 0, 0, '$EE82EE');
INSERT INTO MASTER_PLAN_LAYERS (ID, NAME, IS_GROUP, GROUP_ID, LINE_COLOR)
                        VALUES (1012, 'электричество', 1, 0, '$000000');
COMMIT WORK;

/* ------------------------------------------------------------------------ */

CREATE TABLE MASTER_PLAN_OBJECT_STATUSES (
    ID ID NOT NULL,
    NAME PERSON_NAME NOT NULL /* COLLATE WIN1251 - default */,
    HAS_BACKCOLOR IBBOOL,
    BACKCOLOR INTEGER);
COMMIT WORK;
ALTER TABLE MASTER_PLAN_OBJECT_STATUSES ADD CONSTRAINT PK_MASTER_PLAN_OBJECT_STATUSES PRIMARY KEY (ID) ;
COMMIT WORK;
INSERT INTO MASTER_PLAN_OBJECT_STATUSES (ID, NAME, HAS_BACKCOLOR, BACKCOLOR)
                                 VALUES (0, 'ошибка', 0, 0);
INSERT INTO MASTER_PLAN_OBJECT_STATUSES (ID, NAME, HAS_BACKCOLOR, BACKCOLOR)
                                 VALUES (1, 'проектные', 1, 16766720);
INSERT INTO MASTER_PLAN_OBJECT_STATUSES (ID, NAME, HAS_BACKCOLOR, BACKCOLOR)
                                 VALUES (2, 'проектные демонтируемые', 1, 16711680);
INSERT INTO MASTER_PLAN_OBJECT_STATUSES (ID, NAME, HAS_BACKCOLOR, BACKCOLOR)
                                 VALUES (3, 'выдана справка', 1, 8421504);
INSERT INTO MASTER_PLAN_OBJECT_STATUSES (ID, NAME, HAS_BACKCOLOR, BACKCOLOR)
                                 VALUES (4, 'нанесённые', 0, 0);
COMMIT WORK;

/* ------------------------------------------------------------------------ */

CREATE GENERATOR MP_OBJECTS_GEN;
CREATE GENERATOR MP_OBJECTS_TABLE_VERSION_GEN;
CREATE TABLE MASTER_PLAN_OBJECTS (
    ID ID NOT NULL,
    OBJ_ID VARCHAR(36) /* COLLATE WIN1251 - default */,
    MASTER_PLAN_CLASS_ID ID,
    STATUS SMALLINT,
    DISMANTLED IBBOOL,
    ARCHIVED IBBOOL,
    CONFIRMED IBBOOL,
    ADDRESS STRING1000 /* COLLATE WIN1251 - default */,
    DOC_NUMBER NUMBER_CHAR /* COLLATE WIN1251 - default */,
    DOC_DATE TIMESTAMP,
    REQUEST_NUMBER NUMBER_CHAR /* COLLATE WIN1251 - default */,
    REQUEST_DATE TIMESTAMP,
    UNDERGROUND IBBOOL,
    DIAMETER INTEGER,
    PIPE_COUNT INTEGER,
    VOLTAGE INTEGER,
    MATERIAL STRING255 /* COLLATE WIN1251 - default */,
    TOP STRING255 /* COLLATE WIN1251 - default */,
    BOTTOM STRING255 /* COLLATE WIN1251 - default */,
    FLOOR STRING255 /* COLLATE WIN1251 - default */,
    OWNER STRING255 /* COLLATE WIN1251 - default */,
    DRAW_DATE TIMESTAMP,
    IS_LINE IBBOOL,
    ROTATION INTEGER,
    EZDATA BLOB SUB_TYPE 1 SEGMENT SIZE 4096 /* COLLATE WIN1251 - default */,
    EZ_ID SMALLINT,
    EZ_RECNO INTEGER,
    MINX NUMERIC(15,2) NOT NULL,
    MINY NUMERIC(15,2) NOT NULL,
    MAXX NUMERIC(15,2) NOT NULL,
    MAXY NUMERIC(15,2) NOT NULL,
    LOADED SMALLINT,
    PROJECT_NAME STRING1000 /* COLLATE WIN1251 - default */,
    CUSTOMER_ORGS_ID INTEGER,
    EXECUTOR_ORGS_ID INTEGER,
    OWNER_ORG_ID INTEGER,
    DRAW_ORGS_ID INTEGER,
    DELETED IBBOOL,
    TABLE_VERSION ID,
    DRAWN IBBOOL,
    PROJECTED IBBOOL,
    CERTIF_DATE TIMESTAMP,
    CERTIF_NUMBER NUMBER_CHAR /* COLLATE WIN1251 - default */,
    HAS_CERTIF IBBOOL,
    CHECK_STATE SMALLINT,
    LINKED_OBJ_ID VARCHAR(36) /* COLLATE WIN1251 - default */);
COMMIT WORK;
ALTER TABLE MASTER_PLAN_OBJECTS ADD CONSTRAINT PK_MASTER_PLAN_OBJECTS PRIMARY KEY (ID) ;
COMMIT WORK;

/* ------------------------------------------------------------------------ */

CREATE TABLE MP_CHECK_STATES (
    ID ID NOT NULL,
    NAME STRING100 NOT NULL /* COLLATE WIN1251 - default */,
    STATE_NUMBER INTEGER NOT NULL);
COMMIT WORK;
ALTER TABLE MP_CHECK_STATES ADD CONSTRAINT PK_MP_CHECK_STATES PRIMARY KEY (ID) ;
COMMIT WORK;
INSERT INTO MP_CHECK_STATES (ID, NAME, STATE_NUMBER)
                     VALUES (1, 'Проверен', 1);
INSERT INTO MP_CHECK_STATES (ID, NAME, STATE_NUMBER)
                     VALUES (2, 'Проверить после импорта', 2);
INSERT INTO MP_CHECK_STATES (ID, NAME, STATE_NUMBER)
                     VALUES (3, 'Проверить после редактирования', 3);
INSERT INTO MP_CHECK_STATES (ID, NAME, STATE_NUMBER)
                     VALUES (4, 'Неизвестно', 0);
COMMIT WORK;

/* ------------------------------------------------------------------------ */

ALTER TABLE SQL_QUERIES ADD CONSTRAINT PK_SQL_QUERIES PRIMARY KEY (ID) ;
COMMIT WORK;
INSERT INTO SQL_QUERIES (ID, NAME, SQL_TEXT, COMMENT)
  VALUES (11, 'SQL_GET_PROJECTS_COUNT',
          'SELECT COUNT(ID) FROM PROJECTS WHERE (NOT((:MAXX < MINX) OR (MAXX < :MINX) OR (:MAXY < MINY) OR (MAXY < :MINY)))',
          NULL);
INSERT INTO SQL_QUERIES (ID, NAME, SQL_TEXT, COMMENT)
  VALUES (12, 'SQL_GET_PROJECTS',
          'SELECT ID FROM PROJECTS WHERE (NOT((:MAXX < MINX) OR (MAXX < :MINX) OR (:MAXY < MINY) OR (MAXY < :MINY)))',
          NULL);
UPDATE SQL_QUERIES
SET SQL_TEXT =
'SELECT
'    ID, ADDRESS, DOC_NUMBER, DOC_DATE, AREA, EXECUTOR, VRS, CREATOR, LOT_KINDS_ID, CHECKED, CANCELLED
'FROM
'    ALLOTMENTS
'WHERE
'    (NOT((:XMAX < MINX) OR (MAXX < :XMIN) OR (:YMAX < MINY) OR (MAXY < :YMIN)))
'    AND
'    (LOT_KINDS_ID = :LOT_KINDS_ID)
WHERE (ID = 5);
UPDATE SQL_QUERIES
SET SQL_TEXT =
'SELECT ID, ADDRESS, DOC_NUMBER, DOC_DATE, AREA, EXECUTOR, VRS, CREATOR, LOT_KINDS_ID, CHECKED, CANCELLED 
'FROM ALLOTMENTS
'WHERE
'    (NOT((:XMAX < MINX) OR (MAXX < :XMIN) OR (:YMAX < MINY) OR (MAXY < :YMIN)))
'    AND
'    (LOT_KINDS_ID = :LOT_KINDS_ID)
WHERE (ID = 9);
COMMIT WORK;

/* ------------------------------------------------------------------------ */

ALTER TABLE PROJECT_LAYERS ADD MP_NET_TYPES_ID INTEGER NOT NULL;
ALTER TABLE PROJECT_LAYERS ADD CLASS_ID STRING50 /* COLLATE WIN1251 - default */;

/* ------------------------------------------------------------------------ */

DROP TABLE LAYERS;
