unit uMStKernelStackConsts;

interface

const
   ID_NODETYPE_LOT_ROOT = 0;
   ID_NODETYPE_LOT = 1;
   ID_NODETYPE_LOT_ANNULED_ROOT = 2;
   ID_NODETYPE_LOT_ANNULED = 3;
   ID_NODETYPE_LOT_ACTUAL_ROOT = 4;
   ID_NODETYPE_LOT_ACTUAL = 5;
   ID_NODETYPE_LOT_CONTOUR = 6;
   ID_NODETYPE_LOT_CATEGORIZED_ROOT = 7;
   ID_NODETYPE_LOT_CATEGORIZED = 8;

   ID_NODETYPE_STREET_ROOT = 100;
   ID_NODETYPE_STREET = 101;
   ID_NODETYPE_ADDRESS = 102;

   ID_NODETYPE_PRJ_ROOT = 200;
   ID_NODETYPE_PRJ = 201;

   mstRootNodeTypes: set of Byte = [
     ID_NODETYPE_LOT_ROOT,
     ID_NODETYPE_LOT_ANNULED_ROOT,
     ID_NODETYPE_LOT_ACTUAL_ROOT,
     ID_NODETYPE_LOT_CATEGORIZED_ROOT,
     ID_NODETYPE_STREET_ROOT,
     ID_NODETYPE_PRJ_ROOT
   ];

   mstRootNodeTypesLots: set of Byte = [
     ID_NODETYPE_LOT_ROOT,
     ID_NODETYPE_LOT_ANNULED_ROOT,
     ID_NODETYPE_LOT_ACTUAL_ROOT,
     ID_NODETYPE_LOT_CATEGORIZED_ROOT
   ];

   mstLotNodeTypes: set of Byte = [
     ID_NODETYPE_LOT,
     ID_NODETYPE_LOT_ANNULED,
     ID_NODETYPE_LOT_ACTUAL,
     ID_NODETYPE_LOT_CATEGORIZED
   ];

implementation

end.
