unit uMStKernelConsts;

interface

resourcestring
  sNotConnected = 'Не удалось соединиться с сервером!';
  sMapImageClientError = 'Невозможно обработать изображение планшета!';
  sMapImageServerError = 'Невозможно прочитать изображение планшета!';
  sGISFilesServerError = 'Невозможно прочитать геоданные!';

const
  crCoords = 5;
  crMeasure = 6;
  crText = 7;

  BAD_LOTS = 1;
  ARH_LOTS = 2;
  REG_LOTS = 3;

  id_SnapShot = 101;
  
  clLotArh = 16711680;
  clLotReg = 24576;
  clLotBad = 8388832;

  sError = 'ERROR!!!';
  sOK = 'OK';

  ID_LT_FILE = 1;
  ID_LT_MEMORY = 2;
  ID_LT_IMPORTED = 3;

  SF_ACCOUNT_NAME = 'ACCOUNT_NAME';
  SF_ACT_DATE = 'ACT_DATE';
  SF_ACT_NUMBER = 'ACT_NUMBER';
  SF_ACTUAL = 'ACTUAL';
  SF_ADDRESS = 'ADDRESS';
  SF_ANGLE = 'ANGLE';
  SF_ANNUL_SOURCE = 'ANNUL_SOURCE';
  SF_CANCELLED = 'CANCELLED';
  SF_CHECKED = 'CHECKED';
  SF_CNT_ENABLED = 'CNT_ENABLED';
  SF_CNT_ID = 'CNT_ID';
  SF_CNT_POSITIVE = 'CNT_POSITIVE';
  SF_COLOR = 'COLOR';
  SF_CONTOURS_ID = 'CONTOURS_ID';
  SF_CUSTOMER_ADDRESS_1 = 'CUSTOMER_ADDRESS_1';
  SF_CUSTOMER_ADDRESS_2 = 'CUSTOMER_ADDRESS_2';
  SF_CUSTOMER_DOC_DATE = 'CUSTOMER_DOC_DATE';
  SF_CUSTOMER_DOC_NUMBER = 'CUSTOMER_DOC_NUMBER';
  SF_CUSTOMER_DOC_OWNER = 'CUSTOMER_DOC_OWNER';
  SF_CUSTOMER_DOC_SERIE = 'CUSTOMER_DOC_SERIE';
  SF_CUSTOMER_DOC_TYPE = 'CUSTOMER_DOC_TYPE';
  SF_CUSTOMER_KIND = 'CUSTOMER_KIND';
  SF_CUSTOMER_INFO = 'CUSTOMER_INFO';
  SF_CUSTOMER_INN = 'CUSTOMER_INN';
  SF_CUSTOMER_PHONE = 'CUSTOMER_PHONE';
  SF_DETAILS = 'DETAILS';
  SF_EXT_STREET_ID = 'EXT_STREET_ID';
  SF_FULL_NAME = 'FULL_NAME';
  SF_GROUP_ID = 'GROUP_ID';
  SF_HEIGHT = 'HEIGHT';
  SF_ID = 'ID';
  SF_INFO = 'INFO';
  SF_IS_GROUP = 'IS_GROUP';
  SF_KIOSK_ID = 'KIOSK_ID';
  SF_LAYER_POSITION = 'LAYER_POSITION';
  SF_LAYER_TYPE = 'LAYER_TYPE';
  SF_LETTER_DATE = 'LETTER_DATE';
  SF_LETTER_NUMBER = 'LETTER_NUMBER';
  SF_LIMIT = 'LIMIT';
  SF_LOT_KINDS_ID = 'LOT_KINDS_ID';
  SF_MAXX = 'MAXX';
  SF_MAXY = 'MAXY';
  SF_MINX = 'MINX';
  SF_MINY = 'MINY';
  SF_NAME = 'NAME';
  SF_NET_ID = 'NET_ID';
  SF_NOMENCLATURE = 'NOMENCLATURE';
  SF_OFFICES_ID = 'OFFICES_ID';
  SF_ORDER_DATE = 'ORDER_DATE';
  SF_ORDER_NUMBER = 'ORDER_NUMBER';
  SF_ORDERS_ID = 'ORDERS_ID';
  SF_OBJECT_ADDRESS = 'OBJECT_ADDRESS';
  SF_PEOPLE_ID = 'PEOPLE_ID';
  SF_PHOTO = 'PHOTO';
  SF_PREV_ID = 'PREV_ID';
  SF_PT_ID = 'PT_ID';
  SF_PT_NAME = 'PT_NAME';
  SF_RED_LINES_ID = 'RED_LINES_ID';
  SF_REGION = 'REGION';
  SF_STREET_ID = 'STR_ID';
  SF_STREET_MARK = 'STREET_MARKING_NAME';
  SF_VALUE = 'VALUE';
  SF_VISIBLE = 'VISIBLE';
  SF_VISIBLE_NAME = 'VISIBLE_NAME';
  SF_VRS = 'VRS';
  SF_X = 'X';
  SF_XMAX = 'XMAX';
  SF_XMIN = 'XMIN';
  SF_Y = 'Y';
  SF_YMAX = 'YMAX';
  SF_YMIN = 'YMIN';
  // Слои
  SL_CITYLINE = 'CITYLINE';
  SL_MAP_LAYER = 'M500';
  SL_MAP_IMAGES_LAYER = 'R500';
  SL_STREETS = 'STREETS';
  SL_ADDRESSES = 'ADDRESS';
  SL_LOTS = 'LOTS_REG';
  SL_ACTUAL_LOTS = 'LOTS_ARH';
  SL_ANNULLED_LOTS = 'LOTS_BAD';
  SL_REPORT = 'REPORT';
  SL_PAGES = 'PAGES';
  SL_RED_LINES2 = 'RED_LINES2';
  SL_KIOSK = 'KIOSK';
  SL_WATERMARKS = 'WATERMARKS';

  // Номера картинок
  IMAGE_CONTOUR_ENABLED = 35;
  IMAGE_CONTOUR_DISABLED = 46;
  IMAGE_POINT = 42;
  IMAGE_LOTS_ROOT = 10;
  IMAGE_ACTUAL_LOTS_ROOT = 11;
  IMAGE_ANNULLED_LOTS_ROOT = 12;
  IMAGE_STREET = -1;
  IMAGE_PROJECT = -1;
  IMAGE_ADDRESS = 9;
  IMAGE_ANNULED_LOT = 0;
  IMAGE_ACTUAL_LOT = 1;
  IMAGE_LOT = 2;
  IMAGE_VISIBLECONTOUR = 7;
  IMAGE_INVISIBLECOUNTOUR = 8;
  IMAGE_INVISIBLELOT = 15;
  IMAGE_KIOSK = 14;
  IMAGE_LOT_TRASH = 16;
  IMAGE_LOT_CATEGORIZED = 17;

  WMP_BORDER_COLOR_A = 'BORDER_COLOR_A';
  WMP_BORDER_COLOR_R = 'BORDER_COLOR_R';
  WMP_BORDER_COLOR_G = 'BORDER_COLOR_G';
  WMP_BORDER_COLOR_B = 'BORDER_COLOR_B';
  WMP_BORDER_SIZE = 'BORDER_SIZE';
  WMP_FONT_COLOR_A = 'FONT_COLOR_A';
  WMP_FONT_COLOR_R = 'FONT_COLOR_R';
  WMP_FONT_COLOR_G = 'FONT_COLOR_G';
  WMP_FONT_COLOR_B = 'FONT_COLOR_B';
  WMP_FONT_NAME = 'FONT_NAME';
  WMP_FONT_SIZE = 'FONT_SIZE';
  WMP_INNER_COLOR_A = 'INNER_COLOR_A';
  WMP_INNER_COLOR_R = 'INNER_COLOR_R';
  WMP_INNER_COLOR_G = 'INNER_COLOR_G';
  WMP_INNER_COLOR_B = 'INNER_COLOR_B';
  WMP_TEXT_HEIGHT = 'TEXT_HEIGHT';
  WMP_TEXT_WIDTH = 'TEXT_WIDTH';
  WMP_WATERMARK_TEXT = 'WATERMARK_TEXT';

  function LotColor(const LayerName: String): Integer;

implementation

function LotColor(const LayerName: String): Integer;
begin
  if LayerName = 'LOTS_ARH' then
    Result := $FF0000 //16711680
  else
  if LayerName = 'LOTS_REG' then
    Result := $00FF00//65280
  else
  if LayerName = 'LOTS_BAD' then
    Result := $8000E0 //8388832
  else
  if LayerName = 'SELECTED' then
    Result := $0000FF //255
  else
    Result := 0;
end;



end.
